<a href="https://colab.research.google.com/github/ErdemAslans/WHISPER-TRANSCRIPT-ON-RAG-AND-QA-SYSTEM/blob/main/ALPEDIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/mrdbourke/simple-local-rag/blob/main/00-simple-local-rag.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Create and run a local RAG pipeline from scratch

The goal of this notebook is to build a RAG (Retrieval Augmented Generation) pipeline from scratch and have it run on a local GPU.

Specifically, we'd like to be able to open a PDF file, ask questions (queries) of it and have them answered by a Large Language Model (LLM).

There are frameworks that replicate this kind of workflow, including [LlamaIndex](https://www.llamaindex.ai/) and [LangChain](https://www.langchain.com/), however, the goal of building from scratch is to be able to inspect and customize all the parts.

## What is RAG?

RAG stands for Retrieval Augmented Generation.

It was introduced in the paper [*Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks*](https://arxiv.org/abs/2005.11401).

Each step can be roughly broken down to:

* **Retrieval** - Seeking relevant information from a source given a query. For example, getting relevant passages of Wikipedia text from a database given a question.
* **Augmented** - Using the relevant retrieved information to modify an input to a generative model (e.g. an LLM).
* **Generation** - Generating an output given an input. For example, in the case of an LLM, generating a passage of text given an input prompt.

## Why RAG?

The main goal of RAG is to improve the generation outptus of LLMs.

Two primary improvements can be seen as:
1. **Preventing hallucinations** - LLMs are incredible but they are prone to potential hallucination, as in, generating something that *looks* correct but isn't. RAG pipelines can help LLMs generate more factual outputs by providing them with factual (retrieved) inputs. And even if the generated answer from a RAG pipeline doesn't seem correct, because of retrieval, you also have access to the sources where it came from.
2. **Work with custom data** - Many base LLMs are trained with internet-scale text data. This means they have a great ability to model language, however, they often lack specific knowledge. RAG systems can provide LLMs with domain-specific data such as medical information or company documentation and thus customized their outputs to suit specific use cases.

The authors of the original RAG paper mentioned above outlined these two points in their discussion.

> This work offers several positive societal benefits over previous work: the fact that it is more
strongly grounded in real factual knowledge (in this case Wikipedia) makes it “hallucinate” less
with generations that are more factual, and offers more control and interpretability. RAG could be
employed in a wide variety of scenarios with direct benefit to society, for example by endowing it
with a medical index and asking it open-domain questions on that topic, or by helping people be more
effective at their jobs.

RAG can also be a much quicker solution to implement than fine-tuning an LLM on specific data.



## What kind of problems can RAG be used for?

RAG can help anywhere there is a specific set of information that an LLM may not have in its training data (e.g. anything not publicly accessible on the internet).

For example you could use RAG for:
* **Customer support Q&A chat** - By treating your existing customer support documentation as a resource, when a customer asks a question, you could have a system retrieve relevant documentation snippets and then have an LLM craft those snippets into an answer. Think of this as a "chatbot for your documentation". Klarna, a large financial company, [uses a system like this](https://www.klarna.com/international/press/klarna-ai-assistant-handles-two-thirds-of-customer-service-chats-in-its-first-month/) to save $40M per year on customer support costs.
* **Email chain analysis** - Let's say you're an insurance company with long threads of emails between customers and insurance agents. Instead of searching through each individual email, you could retrieve relevant passages and have an LLM create strucutred outputs of insurance claims.
* **Company internal documentation chat** - If you've worked at a large company, you know how hard it can be to get an answer sometimes. Why not let a RAG system index your company information and have an LLM answer questions you may have? The benefit of RAG is that you will have references to resources to learn more if the LLM answer doesn't suffice.
* **Textbook Q&A** - Let's say you're studying for your exams and constantly flicking through a large textbook looking for answers to your quesitons. RAG can help provide answers as well as references to learn more.

All of these have the common theme of retrieving relevant resources and then presenting them in an understandable way using an LLM.

From this angle, you can consider an LLM a calculator for words.


## Why local?

Privacy, speed, cost.

Running locally means you use your own hardware.

From a privacy standpoint, this means you don't have send potentially sensitive data to an API.

From a speed standpoint, it means you won't necessarily have to wait for an API queue or downtime, if your hardware is running, the pipeline can run.

And from a cost standpoint, running on your own hardware often has a heavier starting cost but little to no costs after that.

Performance wise, LLM APIs may still perform better than an open-source model running locally on general tasks but there are more and more examples appearing of smaller, focused models outperforming larger models.


## Key terms

| Term | Description |
| ----- | ----- |
| **Token** | A sub-word piece of text. For example, "hello, world!" could be split into ["hello", ",", "world", "!"]. A token can be a whole word,<br> part of a word or group of punctuation characters. 1 token ~= 4 characters in English, 100 tokens ~= 75 words.<br> Text gets broken into tokens before being passed to an LLM. |
| **Embedding** | A learned numerical representation of a piece of data. For example, a sentence of text could be represented by a vector with<br> 768 values. Similar pieces of text (in meaning) will ideally have similar values. |
| **Embedding model** | A model designed to accept input data and output a numerical representation. For example, a text embedding model may take in 384 <br>tokens of text and turn it into a vector of size 768. An embedding model can and often is different to an LLM model. |
| **Similarity search/vector search** | Similarity search/vector search aims to find two vectors which are close together in high-demensional space. For example, <br>two pieces of similar text passed through an embedding model should have a high similarity score, whereas two pieces of text about<br> different topics will have a lower similarity score. Common similarity score measures are dot product and cosine similarity. |
| **Large Language Model (LLM)** | A model which has been trained to numerically represent the patterns in text. A generative LLM will continue a sequence when given a sequence. <br>For example, given a sequence of the text "hello, world!", a genertive LLM may produce "we're going to build a RAG pipeline today!".<br> This generation will be highly dependant on the training data and prompt. |
| **LLM context window** | The number of tokens a LLM can accept as input. For example, as of March 2024, GPT-4 has a default context window of 32k tokens<br> (about 96 pages of text) but can go up to 128k if needed. A recent open-source LLM from Google, Gemma (March 2024) has a context<br> window of 8,192 tokens (about 24 pages of text). A higher context window means an LLM can accept more relevant information<br> to assist with a query. For example, in a RAG pipeline, if a model has a larger context window, it can accept more reference items<br> from the retrieval system to aid with its generation. |
| **Prompt** | A common term for describing the input to a generative LLM. The idea of "[prompt engineering](https://en.wikipedia.org/wiki/Prompt_engineering)" is to structure a text-based<br> (or potentially image-based as well) input to a generative LLM in a specific way so that the generated output is ideal. This technique is<br> possible because of a LLMs capacity for in-context learning, as in, it is able to use its representation of language to breakdown <br>the prompt and recognize what a suitable output may be (note: the output of LLMs is probable, so terms like "may output" are used). |




 ## What we're going to build

We're going to build RAG pipeline which enables us to chat with a PDF document, specifically an open-source [nutrition textbook](https://pressbooks.oer.hawaii.edu/humannutrition2/), ~1200 pages long.

You could call our project NutriChat!

We'll write the code to:
1. Open a PDF document (you could use almost any PDF here).
2. Format the text of the PDF textbook ready for an embedding model (this process is known as text splitting/chunking).
3. Embed all of the chunks of text in the textbook and turn them into numerical representation which we can store for later.
4. Build a retrieval system that uses vector search to find relevant chunks of text based on a query.
5. Create a prompt that incorporates the retrieved pieces of text.
6. Generate an answer to a query based on passages from the textbook.

The above steps can broken down into two major sections:
1. Document preprocessing/embedding creation (steps 1-3).
2. Search and answer (steps 4-6).

And that's the structure we'll follow.

It's similar to the workflow outlined on the NVIDIA blog which [details a local RAG pipeline](https://developer.nvidia.com/blog/rag-101-demystifying-retrieval-augmented-generation-pipelines/).

<img src="https://github.com/mrdbourke/simple-local-rag/blob/main/images/simple-local-rag-workflow-flowchart.png?raw=true" alt="flowchart of a local RAG workflow" />

## Requirements and setup

* Local NVIDIA GPU (I used a NVIDIA RTX 4090 on a Windows 11 machine) or Google Colab with access to a GPU.
* Environment setup (see [setup details on GitHub](https://github.com/mrdbourke/simple-local-rag/?tab=readme-ov-file#setup)).
* Data source (for example, a PDF).
* Internet connection (to download the models, but once you have them, it'll run offline).

In [ ]:
# Perform Google Colab installs (if running in Google Colab)
import os

if "COLAB_GPU" in os.environ:
    print("[INFO] Running in Google Colab, installing requirements.")
    !pip install -U torch # requires torch 2.1.1+ (for efficient sdpa implementation)
    !pip install PyMuPDF # for reading PDFs with Python
    !pip install tqdm # for progress bars
    !pip install sentence-transformers # for embedding models
    !pip install accelerate # for quantization model loading
    !pip install bitsandbytes # for quantizing models (less storage space)
    !pip install flash-attn --no-build-isolation # for faster attention mechanism = faster LLM inference
    !pip install gradio

[INFO] Running in Google Colab, installing requirements.
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
  

## 1. Document/Text Processing and Embedding Creation

Ingredients:
* PDF document of choice.
* Embedding model of choice.

Steps:
1. Import PDF document.
2. Process text for embedding (e.g. split into chunks of sentences).
3. Embed text chunks with embedding model.
4. Save embeddings to file for later use (embeddings will store on file for many years or until you lose your hard drive).

### Import PDF Document

This will work with many other kinds of documents.

However, we'll start with PDF since many people have PDFs.

But just keep in mind, text files, email chains, support documentation, articles and more can also work.

We're going to pretend we're nutrition students at the University of Hawai'i, reading through the open-source PDF textbook [*Human Nutrition: 2020 Edition*](https://pressbooks.oer.hawaii.edu/humannutrition2/).

There are several libraries to open PDFs with Python but I found that [PyMuPDF](https://github.com/pymupdf/pymupdf) works quite well in many cases.

First we'll download the PDF if it doesn't exist.

In [ ]:
# Download PDF file
import os
import requests

# Get PDF document
pdf_path = "Restorant.pdf"

# Download PDF if it doesn't already exist
if not os.path.exists(pdf_path):
  print("File doesn't exist, downloading...")

  # The URL of the PDF you want to download
  url = "https://pressbooks.oer.hawaii.edu/humannutrition2/open/download?type=pdf"

  # The local filename to save the downloaded file
  filename = pdf_path

  # Send a GET request to the URL
  response = requests.get(url)

  # Check if the request was successful
  if response.status_code == 200:
      # Open a file in binary write mode and save the content to it
      with open(filename, "wb") as file:
          file.write(response.content)
      print(f"The file has been downloaded and saved as {filename}")
  else:
      print(f"Failed to download the file. Status code: {response.status_code}")
else:
  print(f"File {pdf_path} exists.")

File doesn't exist, downloading...
The file has been downloaded and saved as Restorant.pdf


PDF acquired!

We can import the pages of our PDF to text by first defining the PDF path and then opening and reading it with PyMuPDF (`import fitz`).

We'll write a small helper function to preprocess the text as it gets read. Note that not all text will be read in the same so keep this in mind for when you prepare your text.

We'll save each page to a dictionary and then append that dictionary to a list for ease of use later.

In [ ]:
import re  # Metin düzenlemeleri için kullanılır
from spacy.lang.en import English  # cümle bölme işlemi için spacy
import spacy

# Spacy modelini yükle ve cümleleyici (sentencizer) pipeline'ını ekle
nlp = English()
nlp.add_pipe("sentencizer")

def text_formatter(text: str) -> str:
    """
    Metni küçük formatlama işlemleri yapar: yeni satırları boşlukla değiştir,
    fazla boşlukları temizler ve cümle aralarına doğru boşlukları ekler.
    """
    cleaned_text = text.replace("\n", " ").strip()  # yeni satırları boşlukla değiştir
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text)  # Birden fazla boşluğu tek boşlukla değiştir
    cleaned_text = re.sub(r'\.([A-Z])', r'. \1', cleaned_text)  # ".A" yerine ". A" yap
    return cleaned_text

def open_and_read_pdf(pdf_path: str) -> list[dict]:
    """
    PDF dosyasını açar, metin içeriğini sayfa sayfa okur ve başlıkları ve içerikleri
    düzgün bir şekilde ayrıştırır.

    Parametreler:
        pdf_path (str): Açılacak PDF belgesinin dosya yolu.

    Dönüş:
        list[dict]: Her sayfa için sayfa numarası, karakter sayısı, kelime sayısı, cümle sayısı,
        token sayısı ve metni içeren bir sözlük listesi.
    """
    doc = fitz.open(pdf_path)  # PDF dosyasını aç
    pages_and_texts = []

    for page_number, page in tqdm(enumerate(doc)):  # PDF sayfalarını sırayla oku
        text = page.get_text()  # düz metni al
        text = text_formatter(text)  # metni temizle

        # Her sayfanın bilgilerini listeye ekle
        pages_and_texts.append({
            "page_number": page_number,  # sayfa numarası
            "page_char_count": len(text),  # metindeki karakter sayısı
            "page_word_count": len(text.split(" ")),  # metindeki kelime sayısı
            "page_sentence_count_raw": len(text.split(". ")),  # metindeki cümle sayısı
            "page_token_count": len(text) / 4,  # token sayısı (1 token ≈ 4 karakter)
            "text": text  # formatlanmış metin
        })

    return pages_and_texts

pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)  # PDF'i oku ve metni al
pages_and_texts[:9]  # İlk iki sayfanın sonuçlarını göster


0it [00:00, ?it/s]

[{'page_number': 0,
  'page_char_count': 29,
  'page_word_count': 4,
  'page_sentence_count_raw': 1,
  'page_token_count': 7.25,
  'text': 'Human Nutrition: 2020 Edition'},
 {'page_number': 1,
  'page_char_count': 0,
  'page_word_count': 1,
  'page_sentence_count_raw': 1,
  'page_token_count': 0.0,
  'text': ''},
 {'page_number': 2,
  'page_char_count': 320,
  'page_word_count': 54,
  'page_sentence_count_raw': 1,
  'page_token_count': 80.0,
  'text': 'Human Nutrition: 2020  Edition  UNIVERSITY OF HAWAI‘I AT MĀNOA  FOOD SCIENCE AND HUMAN  NUTRITION PROGRAM  ALAN TITCHENAL, SKYLAR HARA,  NOEMI ARCEO CAACBAY, WILLIAM  MEINKE-LAU, YA-YUN YANG, MARIE  KAINOA FIALKOWSKI REVILLA,  JENNIFER DRAPER, GEMADY  LANGFELDER, CHERYL GIBBY, CHYNA  NICOLE CHUN, AND ALLISON  CALABRESE'},
 {'page_number': 3,
  'page_char_count': 212,
  'page_word_count': 32,
  'page_sentence_count_raw': 1,
  'page_token_count': 53.0,
  'text': 'Human Nutrition: 2020 Edition by University of Hawai‘i at Mānoa Food Science 

Now let's get a random sample of the pages.

In [ ]:
import random

random.sample(pages_and_texts, k=3)

[{'page_number': 1016,
  'page_char_count': 739,
  'page_word_count': 128,
  'page_sentence_count_raw': 4,
  'page_token_count': 184.75,
  'text': 'Image by  Allison  Calabrese /  CC BY 4.0  consumption of sodium in the days leading up to an event and  consume sodium-containing sports drinks during their race or  game. The early signs of hyponatremia include nausea, muscle  cramps, disorientation, and slurred speech. \xa0To learn more about  the sports drinks that can optimize your performance, refer back to  Chapter 3, Water and Electrolytes.  Figure 16.11 The Effect of Exercise on Sodium Levels  Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.\xa0 These activities are  available in the web-based textbook and not available in the  Water and Electrolyte Needs  |  975'},
 {'page_number': 1054,
  'page_char_count': 1936,
  'page_word_count': 312,
  'page_sentence_count_raw'

### Get some stats on the text

Let's perform a rough exploratory data analysis (EDA) to get an idea of the size of the texts (e.g. character counts, word counts etc) we're working with.

The different sizes of texts will be a good indicator into how we should split our texts.

Many embedding models have limits on the size of texts they can ingest, for example, the [`sentence-transformers`](https://www.sbert.net/docs/pretrained_models.html) model [`all-mpnet-base-v2`](https://huggingface.co/sentence-transformers/all-mpnet-base-v2) has an input size of 384 tokens.

This means that the model has been trained in ingest and turn into embeddings texts with 384 tokens (1 token ~= 4 characters ~= 0.75 words).

Texts over 384 tokens which are encoded by this model will be auotmatically reduced to 384 tokens in length, potentially losing some information.

We'll discuss this more in the embedding section.

For now, let's turn our list of dictionaries into a DataFrame and explore it.

In [ ]:
import pandas as pd

df = pd.DataFrame(pages_and_texts)
df.head()

page_number  page_char_count  page_word_count  page_sentence_count_raw  \
0            0               29                4                        1   
1            1                0                1                        1   
2            2              320               54                        1   
3            3              212               32                        1   
4            4              797              145                        2   

   page_token_count                                               text  
0              7.25                      Human Nutrition: 2020 Edition  
1              0.00                                                     
2             80.00  Human Nutrition: 2020  Edition  UNIVERSITY OF ...  
3             53.00  Human Nutrition: 2020 Edition by University of...  
4            199.25  Contents  Preface  University of Hawai‘i at Mā...

In [ ]:
# Get stats
df.describe().round(2)

page_number  page_char_count  page_word_count  page_sentence_count_raw  \
count      1208.00          1208.00          1208.00                  1208.00   
mean        603.50          1148.59           198.89                     9.97   
std         348.86           560.44            95.75                     6.19   
min           0.00             0.00             1.00                     1.00   
25%         301.75           762.75           134.00                     4.00   
50%         603.50          1232.50           215.00                    10.00   
75%         905.25          1605.25           271.25                    14.00   
max        1207.00          2308.00           429.00                    32.00   

       page_token_count  
count           1208.00  
mean             287.15  
std              140.11  
min                0.00  
25%              190.69  
50%              308.12  
75%              401.31  
max              577.00

Okay, looks like our average token count per page is 287.

For this particular use case, it means we could embed an average whole page with the `all-mpnet-base-v2` model (this model has an input capacity of 384).

### Further text processing (splitting pages into sentences)

The ideal way of processing text before embedding it is still an active area of research.

A simple method I've found helpful is to break the text into chunks of sentences.

As in, chunk a page of text into groups of 5, 7, 10 or more sentences (these values are not set in stone and can be explored).

But we want to follow the workflow of:

`Ingest text -> split it into groups/chunks -> embed the groups/chunks -> use the embeddings`

Some options for splitting text into sentences:

1. Split into sentences with simple rules (e.g. split on ". " with `text = text.split(". ")`, like we did above).
2. Split into sentences with a natural language processing (NLP) library such as [spaCy](https://spacy.io/) or [nltk](https://www.nltk.org/).

Why split into sentences?

* Easier to handle than larger pages of text (especially if pages are densely filled with text).
* Can get specific and find out which group of sentences were used to help within a RAG pipeline.

> **Resource:** See [spaCy install instructions](https://spacy.io/usage).

Let's use spaCy to break our text into sentences since it's likely a bit more robust than just using `text.split(". ")`.

In [ ]:
from spacy.lang.en import English  # spacy kütüphanesinden İngilizce dil modeli, kurulum talimatları için https://spacy.io/usage adresine bakın

nlp = English()

# Sentencizer (cümleleyici) pipeline'ını ekle, daha fazla bilgi için https://spacy.io/api/sentencizer/ adresine bakın
nlp.add_pipe("sentencizer")

# Örnek bir belge oluştur
doc = nlp("This is a sentence. This is another sentence.")  # Belgeyi oluştur ve cümlelere ayır
assert len(list(doc.sents)) == 2  # Cümle sayısının 2 olduğunu doğrula

# Belgedeki cümlelere eriş
list(doc.sents)  # Cümleleri liste olarak göster


[This is a sentence., This is another sentence.]

We don't necessarily need to use spaCy, however, it's an open-source library designed to do NLP tasks like this at scale.

So let's run our small sentencizing pipeline on our pages of text.

In [ ]:
def split_into_sections(text):
    """
    Metni başlıklar ve içerikler halinde ayırır.
    """
    sections = re.split(r"(Toplam Gelir|Öne Çıkan Kategoriler|Ayrıntılı Değerlendirme)", text)
    return sections

In [ ]:
# Sentencizer (cümle bölme) işlemini her sayfada uygula ve sonuçları böl
def process_sentences(pages_and_texts):
    """
    Her sayfadaki metni cümlelere ayırır ve bölümleri tespit eder.
    """
    for item in tqdm(pages_and_texts):
        # Cümle bölme işlemi
        doc = nlp(item["text"])
        item["sentences"] = [str(sentence).strip() for sentence in doc.sents]  # Cümleleri diziye ekle
        item["page_sentence_count_spacy"] = len(item["sentences"])  # Cümle sayısını ekle
        # Başlıklar ve içerikleri ayır
        item["sections"] = split_into_sections(item["text"])  # Başlık ve içerik ayırma işlemi
    return pages_and_texts

  0%|          | 0/1208 [00:00<?, ?it/s]

In [ ]:
# Inspect an example
random.sample(pages_and_texts, k=1)

[{'page_number': 710,
  'page_char_count': 944,
  'page_word_count': 152,
  'page_sentence_count_raw': 8,
  'page_token_count': 236.0,
  'text': 'Dietary supplements containing copper typically range from a few  micrograms to 15 mg. 5  Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.\xa0 These activities are  available in the web-based textbook and not available in the  downloadable versions (EPUB, Digital PDF, Print_PDF, or  Open Document).  Learning activities may be used across various mobile  devices, however, for the best user experience it is strongly  recommended that users complete these activities using a  desktop or laptop computer and in Google Chrome.  \xa0 5.\xa0Institute of Medicine (US) Panel on Micronutrients.  (2001). Dietary reference intakes for vitamin A, vitamin K,  arsenic, boron, chromium, copper, iodine, iron,  manganese, molybdenum, nickel, silico

Wonderful!

Now let's turn out list of dictionaries into a DataFrame and get some stats.

In [ ]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

page_number  page_char_count  page_word_count  page_sentence_count_raw  \
count      1208.00          1208.00          1208.00                  1208.00   
mean        603.50          1148.59           198.89                     9.97   
std         348.86           560.44            95.75                     6.19   
min           0.00             0.00             1.00                     1.00   
25%         301.75           762.75           134.00                     4.00   
50%         603.50          1232.50           215.00                    10.00   
75%         905.25          1605.25           271.25                    14.00   
max        1207.00          2308.00           429.00                    32.00   

       page_token_count  page_sentence_count_spacy  
count           1208.00                    1208.00  
mean             287.15                      10.32  
std              140.11                       6.30  
min                0.00                       0.00  
25%              190.69                       5.00  
50%              308.12                      10.00  
75%              401.31                      15.00  
max              577.00                      28.00

For our set of text, it looks like our raw sentence count (e.g. splitting on `". "`) is quite close to what spaCy came up with.

Now we've got our text split into sentences, how about we gorup those sentences?

### Chunking our sentences together

Let's take a step to break down our list of sentences/text into smaller chunks.

As you might've guessed, this process is referred to as **chunking**.

Why do we do this?

1. Easier to manage similar sized chunks of text.
2. Don't overload the embedding models capacity for tokens (e.g. if an embedding model has a capacity of 384 tokens, there could be information loss if you try to embed a sequence of 400+ tokens).
3. Our LLM context window (the amount of tokens an LLM can take in) may be limited and requires compute power so we want to make sure we're using it as well as possible.

Something to note is that there are many different ways emerging for creating chunks of information/text.

For now, we're going to keep it simple and break our pages of sentences into groups of 10 (this number is arbitrary and can be changed, I just picked it because it seemed to line up well with our embedding model capacity of 384).

On average each of our pages has 10 sentences.

And an average total of 287 tokens per page.

So our groups of 10 sentences will also be ~287 tokens long.

This gives us plenty of room for the text to embedded by our `all-mpnet-base-v2` model (it has a capacity of 384 tokens).

To split our groups of sentences into chunks of 10 or less, let's create a function which accepts a list as input and recursively breaks into down into sublists of a specified size.

In [ ]:
# Filtreleme işlemi: minimum token uzunluğu olan metinleri ayıkla
def filter_chunks_by_token_length(pages_and_chunks, min_token_length=5):
    """
    Minimum token uzunluğuna göre parçaları filtreler.
    """
    filtered_chunks = [chunk for chunk in pages_and_chunks if chunk["chunk_token_count"] > min_token_length]
    return filtered_chunks

# Sorguya dayalı sonuç getirme fonksiyonu
def query_based_on_header(query, chunks):
    """
    Sorguya dayalı olarak başlık ve içerikleri getirir.
    Örneğin "Teksas'taki Öne Çıkan Kategoriler" gibi.
    """
    for chunk in chunks:
        if query in chunk:
            return chunk

processed_pages = process_sentences(pages_and_texts)  # Cümleleri işle ve başlıkları böl

In [ ]:
# Sample an example from the group (note: many samples have only 1 chunk as they have <=10 sentences total)
random.sample(pages_and_texts, k=1)

[{'page_number': 643,
  'page_char_count': 1656,
  'page_word_count': 211,
  'page_sentence_count_raw': 31,
  'page_token_count': 414.0,
  'text': 'angiogenic, antioxidant, and anti-carcinogenic properties of a novel  anthocyanin-rich berry extract formula. Biochemistry. Biokhimiia, 69(1),  75–80,  1  p  preceding  75.  https:/ /doi.org/10.1023/ b:biry.0000016355.19999.93  Flavonoids.  (2014,  April  28).  Linus  Pauling  Institute.  https:/ /lpi.oregonstate.edu/mic/dietary-factors/ phytochemicals/flavonoids  Goto, T., Takahashi, N., Hirai, S., & Kawada, T. (2010). Various  Terpenoids Derived from Herbal and Dietary Plants Function as  PPAR Modulators and Regulate Carbohydrate and Lipid Metabolism.  PPAR Research, 2010. https:/ /doi.org/10.1155/2010/483958  Higdon, J. V., Delage, B., Williams, D. E., & Dashwood, R. H. (2007).  Cruciferous Vegetables and Human Cancer Risk: Epidemiologic  Evidence and Mechanistic Basis. Pharmacological Research\u202f: The  Official Journal of the Italian

In [ ]:
# Create a DataFrame to get stats
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

page_number  page_char_count  page_word_count  page_sentence_count_raw  \
count      1208.00          1208.00          1208.00                  1208.00   
mean        603.50          1148.59           198.89                     9.97   
std         348.86           560.44            95.75                     6.19   
min           0.00             0.00             1.00                     1.00   
25%         301.75           762.75           134.00                     4.00   
50%         603.50          1232.50           215.00                    10.00   
75%         905.25          1605.25           271.25                    14.00   
max        1207.00          2308.00           429.00                    32.00   

       page_token_count  page_sentence_count_spacy  num_chunks  
count           1208.00                    1208.00     1208.00  
mean             287.15                      10.32        1.38  
std              140.11                       6.30        0.56  
min                0.00                       0.00        0.00  
25%              190.69                       5.00        1.00  
50%              308.12                      10.00        1.00  
75%              401.31                      15.00        2.00  
max              577.00                      28.00        3.00

Note how the average number of chunks is around 1.5, this is expected since many of our pages only contain an average of 10 sentences.

### Splitting each chunk into its own item

We'd like to embed each chunk of sentences into its own numerical representation.

So to keep things clean, let's create a new list of dictionaries each containing a single chunk of sentences with relative information such as page number as well statistics about each chunk.

In [ ]:
# View a random sample
random.sample(pages_and_chunks, k=1)

[{'page_number': 280,
  'sentence_chunk': 'recommended that users complete these activities using a desktop or laptop computer and in Google Chrome. \xa0 An interactive or media element has been excluded from this version of the text. You can view it online here: http:/ /pressbooks.oer.hawaii.edu/ humannutrition2/?p=175 \xa0 An interactive or media element has been excluded from this version of the text. You can view it online here: http:/ /pressbooks.oer.hawaii.edu/ humannutrition2/?p=175 Introduction | 239',
  'chunk_char_count': 464,
  'chunk_word_count': 67,
  'chunk_token_count': 116.0}]

Excellent!

Now we've broken our whole textbook into chunks of 10 sentences or less as well as the page number they came from.

This means we could reference a chunk of text and know its source.

Let's get some stats about our chunks.

In [ ]:
# Get stats about our chunks
df = pd.DataFrame(pages_and_chunks)
df.describe().round(2)

page_number  chunk_char_count  chunk_word_count  chunk_token_count
count      1664.00           1664.00           1664.00            1664.00
mean        626.21            813.97            124.83             203.49
std         349.25            514.04             81.15             128.51
min           0.00             10.00              3.00               2.50
25%         323.00            305.75             45.00              76.44
50%         631.50            837.00            127.00             209.25
75%         933.25           1262.50            195.00             315.62
max        1207.00           1930.00            321.00             482.50

Hmm looks like some of our chunks have quite a low token count.

How about we check for samples with less than 30 tokens (about the length of a sentence) and see if they are worth keeping?

In [ ]:
# min_token_length = 5

# # Önce kaç satır olduğunu kontrol edelim
# filtered_df = df[df["chunk_token_count"] <= min_token_length]

# # Mevcut satır sayısından fazla örnek almak istersek, örnekleme sayısını ayarlayalım
# sample_size = min(2, len(filtered_df))

# # Örnekleme yapalım ve her satırı işleyelim
# for row in filtered_df.sample(sample_size).iterrows():
#     print(f'Chunk token count: {row[1]["chunk_token_count"]} | Text: {row[1]["sentence_chunk"]}')


Chunk token count: 3.75 | Text: 640 | Magnesium
Chunk token count: 3.25 | Text: Calcium | 619


Looks like many of these are headers and footers of different pages.

They don't seem to offer too much information.

Let's filter our DataFrame/list of dictionaries to only include chunks with over 30 tokens in length.

In [ ]:
# pages_and_chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")
# # pages_and_chunks_over_min_token_len[:2]

[{'page_number': 0,
  'sentence_chunk': 'Human Nutrition: 2020 Edition',
  'chunk_char_count': 29,
  'chunk_word_count': 4,
  'chunk_token_count': 7.25},
 {'page_number': 2,
  'sentence_chunk': 'Human Nutrition: 2020 Edition UNIVERSITY OF HAWAI‘I AT MĀNOA FOOD SCIENCE AND HUMAN NUTRITION PROGRAM ALAN TITCHENAL, SKYLAR HARA, NOEMI ARCEO CAACBAY, WILLIAM MEINKE-LAU, YA-YUN YANG, MARIE KAINOA FIALKOWSKI REVILLA, JENNIFER DRAPER, GEMADY LANGFELDER, CHERYL GIBBY, CHYNA NICOLE CHUN, AND ALLISON CALABRESE',
  'chunk_char_count': 308,
  'chunk_word_count': 42,
  'chunk_token_count': 77.0}]

Smaller chunks filtered!

Time to embed our chunks of text!

### Embedding our text chunks

While humans understand text, machines understand numbers best.

An [embedding](https://vickiboykis.com/what_are_embeddings/index.html) is a broad concept.

But one of my favourite and simple definitions is "a useful numerical representation".

The most powerful thing about modern embeddings is that they are *learned* representations.

Meaning rather than directly mapping words/tokens/characters to numbers directly (e.g. `{"a": 0, "b": 1, "c": 3...}`), the numerical representation of tokens is learned by going through large corpuses of text and figuring out how different tokens relate to each other.

Ideally, embeddings of text will mean that similar meaning texts have similar numerical representation.

> **Note:** Most modern NLP models deal with "tokens" which can be considered as multiple different sizes and combinations of words and characters rather than always whole words or single characters. For example, the string `"hello world!"` gets mapped to the token values `{15339: b'hello', 1917: b' world', 0: b'!'}` using [Byte pair encoding](https://en.wikipedia.org/wiki/Byte_pair_encoding) (or BPE via OpenAI's [`tiktoken`](https://github.com/openai/tiktoken) library). Google has a tokenization library called [SentencePiece](https://github.com/google/sentencepiece).

Our goal is to turn each of our chunks into a numerical representation (an embedding vector, where a vector is a sequence of numbers arranged in order).

Once our text samples are in embedding vectors, us humans will no longer be able to understand them.

However, we don't need to.

The embedding vectors are for our computers to understand.

We'll use our computers to find patterns in the embeddings and then we can use their text mappings to further our understanding.

Enough talking, how about we import a text embedding model and see what an embedding looks like.

To do so, we'll use the [`sentence-transformers`](https://www.sbert.net/docs/installation.html) library which contains many pre-trained embedding models.

Specifically, we'll get the `all-mpnet-base-v2` model (you can see the model's intended use on the [Hugging Face model card](https://huggingface.co/sentence-transformers/all-mpnet-base-v2#intended-uses)).

In [ ]:
!pip install numpy
!pip install sentence-transformers

In [ ]:
!pip install --upgrade torch torchvision
!pip install --upgrade transformers
!pip install torchvision

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 100.0 MB/s eta 0:00:00
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.18.1+cu121
    Uninstalling torchvision-0.18.1+cu121:
      Successfully uninstalled torchvision-0.18.1+cu121
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 115.8 MB/s eta 0:00:00
  Attempting uninstall: transformers
    Found existing installation: transformers 4.42.4
    Uninstalling transformers-4.42.4:
      Successfully uninstalled transformers-4.42.4


In [ ]:
# Requires !pip install sentence-transformers
from sentence_transformers import SentenceTransformer

# "roberta-large" modelini kullanarak GPU üzerinde çalıştırma
embedding_model = SentenceTransformer(model_name_or_path="roberta-large",
                                      device="cuda")  # GPU'yu kullanacak şekilde ayarla

# Tüm metinleri içeren bir liste (örneğin tüm PDF metinleri)
all_sentences = [item['text'] for item in pages_and_texts]

# Batch işlemi ile embedding'leri hesapla
text_chunk_embeddings = embedding_model.encode(all_sentences,
                                               batch_size=32,  # Batch boyutu, GPU performansını artırmak için kullanılıyor
                                               convert_to_tensor=True)  # Tensor olarak döndürmek için kullanılır

# Embedding'leri saklamak için bir dict oluştur
embeddings_dict = dict(zip(all_sentences, text_chunk_embeddings))

# Örnek olarak embedding'leri görüntüleyelim
for sentence, embedding in embeddings_dict.items():
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Sentence: The Sentences Transformers library provides an easy and open-source way to create embeddings.
Embedding: [-2.07981188e-02  3.03164795e-02 -2.01218072e-02  6.86483085e-02
 -2.55255401e-02 -8.47692974e-03 -2.07088728e-04 -6.32377863e-02
  2.81606447e-02 -3.33353542e-02  3.02634742e-02  5.30720390e-02
 -5.03526330e-02  2.62288321e-02  3.33313867e-02 -4.51578684e-02
  3.63044105e-02 -1.37114769e-03 -1.20171010e-02  1.14946850e-02
  5.04510738e-02  4.70857024e-02  2.11913269e-02  5.14607392e-02
 -2.03746352e-02 -3.58889922e-02 -6.67880289e-04 -2.94393245e-02
  4.95858602e-02 -1.05640031e-02 -1.52013926e-02 -1.31751515e-03
  4.48197126e-02  1.56023093e-02  8.60379714e-07 -1.21392251e-03
 -2.37978455e-02 -9.09413560e-04  7.34486757e-03 -2.53935461e-03
  5.23370281e-02 -4.68043573e-02  1.66214760e-02  4.71579768e-02
 -4.15599681e-02  9.01928695e-04  3.60278450e-02  3.42215225e-02
  9.68227163e-02  5.94829172e-02 -1.64984949e-02 -3.51249948e-02
  5.92521718e-03 -7.07982690e-04 -2.4103

Woah! That's a lot of numbers.

How about we do just once sentence?

In [ ]:
import faiss
import numpy as np

# Embedding'leri numpy dizisine çevir
embedding_array = np.array([embedding.cpu().numpy() for embedding in text_chunk_embeddings])

# FAISS indeksini oluştur (embedding boyutuna göre)
index = faiss.IndexFlatL2(embedding_array.shape[1])

# Embedding'leri indekse ekle
index.add(embedding_array)

# Sorgu cümlesinin embedding'ini hesaplayalım
query_sentence = "Teksas'taki gelir nedir?"
query_embedding = embedding_model.encode([query_sentence], convert_to_tensor=True).cpu().numpy()

# FAISS ile sorguya en yakın embedding'i bulalım
distances, indices = index.search(query_embedding, k=1)  # En yakın 1 sonucu getir
closest_sentence = all_sentences[indices[0][0]]

print(f"Closest match: {closest_sentence}")

Sentence: Yo! How cool are embeddings?
Embedding:
[-1.97447799e-02 -4.51087346e-03 -4.98481654e-03  6.55444637e-02
 -9.87675134e-03  2.72835009e-02  3.66426669e-02 -3.30220396e-03
  8.50083586e-03  8.24953057e-03 -2.28497051e-02  4.02430259e-02
 -5.75200766e-02  6.33692369e-02  4.43207435e-02 -4.49507199e-02
  1.25284335e-02 -2.52012145e-02 -3.55292484e-02  1.29559236e-02
  8.67022295e-03 -1.92917492e-02  3.55632650e-03  1.89506095e-02
 -1.47128282e-02 -9.39843431e-03  7.64171127e-03  9.62186884e-03
 -5.98929124e-03 -3.90169173e-02 -5.47823943e-02 -5.67457918e-03
  1.11644939e-02  4.08067033e-02  1.76319077e-06  9.15296283e-03
 -8.77259858e-03  2.39383057e-02 -2.32784543e-02  8.04999769e-02
  3.19176316e-02  5.12598688e-03 -1.47708477e-02 -1.62524693e-02
 -6.03213198e-02 -4.35689241e-02  4.51211818e-02 -1.79053899e-02
  2.63367314e-02 -3.47866863e-02 -8.89175665e-03 -5.47674857e-02
 -1.24372598e-02 -2.38606799e-02  8.33496526e-02  5.71242087e-02
  1.13328611e-02 -1.49594182e-02  9.2037

Nice! We've now got a way to numerically represent each of our chunks.

Our embedding has a shape of `(768,)` meaning it's a vector of 768 numbers which represent our text in high-dimensional space, too many for a human to comprehend but machines love high-dimensional space.

> **Note:** No matter the size of the text input to our `all-mpnet-base-v2` model, it will be turned into an embedding size of `(768,)`. This value is fixed. So whether a sentence is 1 token long or 1000 tokens long, it will be truncated/padded with zeros to size 384 and then turned into an embedding vector of size `(768,)`. Of course, other embedding models may have different input/output shapes.

How about we add an embedding field to each of our chunk items?

Let's start by trying to create embeddings on the CPU, we'll time it with the `%%time` magic to see how long it takes.

In [ ]:
%%time

# Uncomment to see how long it takes to create embeddings on CPU
# # Make sure the model is on the CPU
# embedding_model.to("cpu")

# # Embed each chunk one by one
# for item in tqdm(pages_and_chunks_over_min_token_len):
#     item["embedding"] = embedding_model.encode(item["sentence_chunk"])

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 6.68 µs


Ok not too bad... but this would take a *really* long time if we had a larger dataset.

Now let's see how long it takes to create the embeddings with a GPU.

In [ ]:
# %%time

# # Send the model to the GPU
# embedding_model.to("cuda") # requires a GPU installed, for reference on my local machine, I'm using a NVIDIA RTX 4090

# # Create embeddings one by one on the GPUA
for item in tqdm(pages_and_chunks_over_min_token_len):
#     item["embedding"] = embedding_model.encode(item["sentence_chunk"])

  0%|          | 0/1651 [00:00<?, ?it/s]

CPU times: user 1min 6s, sys: 425 ms, total: 1min 7s
Wall time: 25.7 s


Woah! Looks like the embeddings get created much faster (~10x faster on my machine) on the GPU!

You'll likely notice this trend with many of your deep learning workflows. If you have access to a GPU, especially a NVIDIA GPU, you should use one if you can.

But what if I told you we could go faster again?

You see many modern models can handle batched predictions.

This means computing on multiple samples at once.

Those are the types of operations where a GPU flourishes!

We can perform batched operations by turning our target text samples into a single list and then passing that list to our embedding model.

In [ ]:
%%time

# Embed all texts in batches
text_chunk_embeddings = embedding_model.encode(text_chunks,
                                               batch_size=32, # you can use different batch sizes here for speed/performance, I found 32 works well for this use case
                                               convert_to_tensor=True) # optional to return embeddings as tensor instead of array

text_chunk_embeddings

CPU times: user 15.8 s, sys: 114 ms, total: 15.9 s
Wall time: 12.9 s


tensor([[ 0.0441,  0.0924,  0.0033,  ..., -0.0139, -0.0256,  0.0086],
        [ 0.0674,  0.0902, -0.0051,  ..., -0.0221, -0.0232,  0.0126],
        [ 0.0552,  0.0592, -0.0166,  ..., -0.0120, -0.0103,  0.0227],
        ...,
        [ 0.0888,  0.0139, -0.0093,  ..., -0.0400, -0.0685, -0.0235],
        [ 0.0674, -0.0144, -0.0400,  ..., -0.0368, -0.0426, -0.0692],
        [ 0.0864, -0.0125, -0.0113,  ..., -0.0522, -0.0337, -0.0299]],
       device='cuda:0')

That's what I'm talking about!

A ~4x improvement (on my GPU) in speed thanks to batched operations.

So the tip here is to use a GPU when you can and use batched operations if you can too.

Now let's save our chunks and their embeddings so we could import them later if we wanted.

### Save embeddings to file

Since creating embeddings can be a timely process (not so much for our case but it can be for more larger datasets), let's turn our `pages_and_chunks_over_min_token_len` list of dictionaries into a DataFrame and save it.

In [ ]:
# Save embeddings to file
text_chunks_and_embeddings_df = pd.DataFrame(pages_and_chunks_over_min_token_len)
embeddings_df_save_path = "text_chunks_and_embeddings_df.csv"
text_chunks_and_embeddings_df.to_csv(embeddings_df_save_path, index=False)

And we can make sure it imports nicely by loading it.

In [ ]:
# Import saved file and view
text_chunks_and_embedding_df_load = pd.read_csv(embeddings_df_save_path)
text_chunks_and_embedding_df_load.head()

page_number                                     sentence_chunk  \
0            0                      Human Nutrition: 2020 Edition   
1            2  Human Nutrition: 2020 Edition UNIVERSITY OF HA...   
2            3  Human Nutrition: 2020 Edition by University of...   
3            4  Contents Preface University of Hawai‘i at Māno...   
4            5  Lifestyles and Nutrition University of Hawai‘i...   

   chunk_char_count  chunk_word_count  chunk_token_count  \
0                29                 4               7.25   
1               308                42              77.00   
2               210                30              52.50   
3               766               114             191.50   
4               941               142             235.25   

                                           embedding  
0  [ 4.41241600e-02  9.24154595e-02  3.28842294e-...  
1  [ 6.74242675e-02  9.02281180e-02 -5.09549584e-...  
2  [ 5.52156232e-02  5.92139065e-02 -1.66167300e-...  
3  [ 2.79801823e-02  3.39813717e-02 -2.06426494e-...  
4  [ 6.82566985e-02  3.81274670e-02 -8.46854597e-...

### Chunking and embedding questions

> **Which embedding model should I use?**

This depends on many factors. My best advice is to experiment, experiment, experiment!

If you want the model to run locally, you'll have to make sure it's feasible to run on your own hardware.

A good place to see how different models perform on a wide range of embedding tasks is the [Hugging Face Massive Text Embedding Benchmark (MTEB) Leaderboard](https://huggingface.co/spaces/mteb/leaderboard).

> **What other forms of text chunking/splitting are there?**

There are a fair few options here too. We've kept it simple with groups of sentences.

For more, [Pinecone has a great guide on different kinds of chunking](https://www.pinecone.io/learn/chunking-strategies/) including for different kinds of data such as markdown and LaTeX.

Libraries such as [LangChain also have a good amount of in-built text splitting options](https://python.langchain.com/docs/modules/data_connection/document_transformers/).

> **What should I think about when creating my embeddings?**

Our model turns text inputs up to 384 tokens long in embedding vectors of size 768.

Generally, the larger the vector size, the more information that gets encoded into the embedding (however, this is not always the case, as smaller, better models can outperform larger ones).

Though with larger vector sizes comes larger storage and compute requirements.

Our model is also relatively small (420MB) in size compared to larger models that are available.

Larger models may result in better performance but will also require more compute.

So some things to think about:
* Size of input - If you need to embed longer sequences, choose a model with a larger input capacity.
* Size of embedding vector - Larger is generally a better representation but requires more compute/storage.
* Size of model - Larger models generally result in better embeddings but require more compute power/time to run.
* Open or closed - Open models allow you to run them on your own hardware whereas closed models can be easier to setup but require an API call to get embeddings.

> **Where should I store my embeddings?**

If you've got a relatively small dataset, for example, under 100,000 examples (this number is rough and only based on first hand experience), `np.array` or `torch.tensor` can work just fine as your dataset.

But if you've got a production system and want to work with 100,000+ embeddings, you may want to look into a [vector database]( https://en.wikipedia.org/wiki/Vector_database) (these have become very popular lately and there are many offerings).

### Document Ingestion and Embedding Creation Extensions

One major extension to the workflow above would to functionize it.

Or turn it into a script.

As in, take all the functionality we've created and package it into a single process (e.g. go from document -> embeddings file).

So you could input a document on one end and have embeddings come out the other end. The hardest part of this is knowing what kind of preprocessing your text may need before it's turned into embeddings. Cleaner text generally means better results.



## 2. RAG - Search and Answer

We discussed RAG briefly in the beginning but let's quickly recap.

RAG stands for Retrieval Augmented Generation.

Which is another way of saying "given a query, search for relevant resources and answer based on those resources".

Let's breakdown each step:
* **Retrieval** - Get relevant resources given a query. For example, if the query is "what are the macronutrients?" the ideal results will contain information about protein, carbohydrates and fats (and possibly alcohol) rather than information about which tractors are the best for farming (though that is also cool information).
* **Augmentation** - LLMs are capable of generating text given a prompt. However, this generated text is designed to *look* right. And it often has some correct information, however, they are prone to hallucination (generating a result that *looks* like legit text but is factually wrong). In augmentation, we pass relevant information into the prompt and get an LLM to use that relevant information as the basis of its generation.
* **Generation** - This is where the LLM will generate a response that has been flavoured/augmented with the retrieved resources. In turn, this not only gives us a potentially more correct answer, it also gives us resources to investigate more (since we know which resources went into the prompt).

The whole idea of RAG is to get an LLM to be more factually correct based on your own input as well as have a reference to where the generated output may have come from.

This is an incredibly helpful tool.

Let's say you had 1000s of customer support documents.

You could use RAG to generate direct answers to questions with links to relevant documentation.

Or you were an insurance company with large chains of claims emails.

You could use RAG to answer questions about the emails with sources.

One helpful analogy is to think of LLMs as calculators for words.

With good inputs, the LLM can sort them into helpful outputs.

How?

It starts with better search.

### Similarity search

Similarity search or semantic search or vector search is the idea of searching on *vibe*.

If this sounds like woo, woo. It's not.

Perhaps searching via *meaning* is a better analogy.

With keyword search, you are trying to match the string "apple" with the string "apple".

Whereas with similarity/semantic search, you may want to search "macronutrients functions".

And get back results that don't necessarily contain the words "macronutrients functions" but get back pieces of text that match that meaning.

> **Example:** Using similarity search on our textbook data with the query "macronutrients function" returns a paragraph that starts with:
>
>*There are three classes of macronutrients: carbohydrates, lipids, and proteins. These can be metabolically processed into cellular energy. The energy from macronutrients comes from their chemical bonds. This chemical energy is converted into cellular energy that is then utilized to perform work, allowing our bodies to conduct their basic functions.*
>
> as the first result. How cool!

If you've ever used Google, you know this kind of workflow.

But now we'd like to perform that across our own data.

Let's import our embeddings we created earlier (tk -link to embedding file) and prepare them for use by turning them into a tensor.

In [ ]:
import random

import torch
import numpy as np
import pandas as pd

# Kullanılabilir bir GPU varsa cihazı CUDA olarak ayarla, yoksa CPU kullan
device = "cuda" if torch.cuda.is_available() else "cpu"

# Metinleri ve gömme vektörlerini içeren CSV dosyasını yükle
text_chunks_and_embedding_df = pd.read_csv("text_chunks_and_embeddings_df.csv")

# Embedding sütununu yeniden np.array'e dönüştür (CSV'ye kaydedildiğinde string'e dönüşmüştü)
text_chunks_and_embedding_df["embedding"] = text_chunks_and_embedding_df["embedding"].apply(lambda x: np.fromstring(x.strip("[]"), sep=" "))

# Metinler ve embedding verilerini içeren DataFrame'i dict listesine dönüştür
pages_and_chunks = text_chunks_and_embedding_df.to_dict(orient="records")

# Embedding'leri torch tensora dönüştür ve cihaza gönder (Not: NumPy dizileri float64, torch tensörleri varsayılan olarak float32'dir)
embeddings = torch.tensor(np.array(text_chunks_and_embedding_df["embedding"].tolist()), dtype=torch.float32).to(device)
embeddings.shape


torch.Size([1651, 768])

In [ ]:
text_chunks_and_embedding_df.head()

page_number                                     sentence_chunk  \
0            0                      Human Nutrition: 2020 Edition   
1            2  Human Nutrition: 2020 Edition UNIVERSITY OF HA...   
2            3  Human Nutrition: 2020 Edition by University of...   
3            4  Contents Preface University of Hawai‘i at Māno...   
4            5  Lifestyles and Nutrition University of Hawai‘i...   

   chunk_char_count  chunk_word_count  chunk_token_count  \
0                29                 4               7.25   
1               308                42              77.00   
2               210                30              52.50   
3               766               114             191.50   
4               941               142             235.25   

                                           embedding  
0  [0.04412416, 0.0924154595, 0.00328842294, -0.0...  
1  [0.0674242675, 0.090228118, -0.00509549584, -0...  
2  [0.0552156232, 0.0592139065, -0.01661673, -0.0...  
3  [0.0279801823, 0.0339813717, -0.0206426494, 0....  
4  [0.0682566985, 0.038127467, -0.00846854597, -0...

In [ ]:
embeddings[0]

tensor([ 4.4124e-02,  9.2415e-02,  3.2884e-03, -1.6667e-02,  6.4126e-02,
         2.3135e-03, -1.1477e-02,  5.2484e-02,  5.8630e-02,  6.9388e-03,
         8.3775e-02,  2.5904e-02, -1.8287e-03,  5.7680e-02,  4.4049e-02,
        -5.2161e-02,  6.5268e-02, -2.0710e-03, -3.9890e-02,  3.8001e-03,
        -7.4296e-02,  2.3259e-02,  2.9309e-02, -1.5127e-02, -5.3632e-02,
         4.7621e-02,  1.5748e-02,  3.7696e-02, -1.4147e-02, -3.8589e-02,
        -7.5978e-03,  3.6414e-02, -1.5818e-02, -5.4194e-02,  1.7160e-06,
        -3.4951e-02, -4.0989e-02,  6.4031e-02, -7.2408e-02,  2.8286e-02,
         6.6285e-02, -7.4168e-02, -1.4103e-02, -7.1238e-03,  2.2020e-02,
         2.5916e-02,  4.2869e-02,  3.1436e-02, -1.4460e-02, -1.5380e-02,
         1.6089e-02, -3.8460e-02,  1.2981e-02, -6.3244e-03,  7.1073e-03,
         1.1588e-02, -3.2230e-02,  4.4437e-02,  5.0358e-02,  1.6043e-02,
         1.1437e-02,  8.3545e-02,  1.1990e-02,  6.3564e-03, -1.2832e-02,
         7.0283e-02, -8.8527e-03, -7.5059e-02,  2.1

Nice!

Now let's prepare another instance of our embedding model. Not because we have to but because we'd like to make it so you can start the notebook from the cell above.

In [ ]:
from sentence_transformers import util, SentenceTransformer

embedding_model = SentenceTransformer(model_name_or_path="all-mpnet-base-v2",
                                      device=device) # choose the device to load the model to

Embedding model ready!

Time to perform a semantic search.

Let's say you were studying the macronutrients.

And wanted to search your textbook for "macronutrients functions".

Well, we can do so with the following steps:
1. Define a query string (e.g. `"macronutrients functions"`) - note: this could be anything, specific or not.
2. Turn the query string in an embedding with same model we used to embed our text chunks.
3. Perform a [dot product](https://pytorch.org/docs/stable/generated/torch.dot.html) or [cosine similarity](https://en.wikipedia.org/wiki/Cosine_similarity) function between the text embeddings and the query embedding (we'll get to what these are shortly) to get similarity scores.
4. Sort the results from step 3 in descending order (a higher score means more similarity in the eyes of the model) and use these values to inspect the texts.

Easy!


In [ ]:
# 1. Define the query
# Note: This could be anything. But since we're working with a nutrition textbook, we'll stick with nutrition-based queries.
query = "Rezervasyon sorunu yaşadım"
print(f"Query: {query}")

# 2. Embed the query to the same numerical space as the text examples
# Note: It's important to embed your query with the same model you embedded your examples with.
query_embedding = embedding_model.encode(query, convert_to_tensor=True)

# 3. Get similarity scores with the dot product (we'll time this for fun)
from time import perf_counter as timer

start_time = timer()
dot_scores = util.dot_score(a=query_embedding, b=embeddings)[0]
end_time = timer()

print(f"Time take to get scores on {len(embeddings)} embeddings: {end_time-start_time:.5f} seconds.")

# 4. Get the top-k results (we'll keep this to 5)
top_results_dot_product = torch.topk(dot_scores, k=5)
top_results_dot_product

Query: Rezervasyon sorunu yaşadım
Time take to get scores on 1651 embeddings: 0.00267 seconds.


torch.return_types.topk(
values=tensor([0.2291, 0.2250, 0.2227, 0.2116, 0.2113], device='cuda:0'),
indices=tensor([  33, 1200, 1198,   27, 1264], device='cuda:0'))

Woah!! Now that was fast!

~0.00008 seconds to perform a dot product comparison across 1680 embeddings on my machine (NVIDIA RTX 4090 GPU).

GPUs are optimized for these kinds of operations.

So even if you we're to increase our embeddings by 100x (1680 -> 168,000), an exhaustive dot product operation would happen in ~0.008 seconds (assuming linear scaling).

Heck, let's try it.

In [ ]:
larger_embeddings = torch.randn(100*embeddings.shape[0], 768).to(device)
print(f"Embeddings shape: {larger_embeddings.shape}")

# Perform dot product across 168,000 embeddings
start_time = timer()
dot_scores = util.dot_score(a=query_embedding, b=larger_embeddings)[0]
end_time = timer()

print(f"Time take to get scores on {len(larger_embeddings)} embeddings: {end_time-start_time:.5f} seconds.")

Embeddings shape: torch.Size([165100, 768])
Time take to get scores on 165100 embeddings: 0.02071 seconds.


Wow. That's quick!

That means we can get pretty far by just storing our embeddings in `torch.tensor` for now.

However, for *much* larger datasets, we'd likely look at a dedicated vector database/indexing libraries such as [Faiss](https://github.com/facebookresearch/faiss).

Let's check the results of our original similarity search.

[`torch.topk`](https://pytorch.org/docs/stable/generated/torch.topk.html) returns a tuple of values (scores) and indicies for those scores.

The indicies relate to which indicies in the `embeddings` tensor have what scores in relation to the query embedding (higher is better).

We can use those indicies to map back to our text chunks.

First, we'll define a small helper function to print out wrapped text (so it doesn't print a whole text chunk as a single line).

In [ ]:
# Define helper function to print wrapped text
import textwrap

def print_wrapped(text, wrap_length=80):
    wrapped_text = textwrap.fill(text, wrap_length)
    print(wrapped_text)

Now we can loop through the `top_results_dot_product` tuple and match up the scores and indicies and then use those indicies to index on our `pages_and_chunks` variable to get the relevant text chunk.

Sounds like a lot but we can do it!

In [ ]:
print(f"Query: '{query}'\n")
print("Results:")
# Loop through zipped together scores and indicies from torch.topk
for score, idx in zip(top_results_dot_product[0], top_results_dot_product[1]):
    print(f"Score: {score:.4f}")
    # Print relevant sentence chunk (since the scores are in descending order, the most relevant chunk will be first)
    print("Text:")
    print_wrapped(pages_and_chunks[idx]["sentence_chunk"])
    # Print the page number too so we can reference the textbook further (and check the results)
    print(f"Page number: {pages_and_chunks[idx]['page_number']}")
    print("\n")

Query: 'Rezervasyon sorunu yaşadım'

Results:
Score: 0.2291
Text:
Ya-Yun Yang Ya-Yun is a Graduate Assistant in the Distance Education Program for
the College of Tropical Agriculture and Human Resources. She is currently a PhD
student in Learning Design and Technology (LTEC) at the University of Hawai‘i at
Mānoa. Christina Gar Lai Young About the Contributors | xxxv
Page number: 34


Score: 0.2250
Text:
https:/ /www.kokuahawaiifoundation.org/aina. Accessed February 16, 2018. 868 |
Introduction
Page number: 909


Score: 0.2227
Text:
Image by Brytni K-aloha / CC BY 4.0 Introduction UNIVERSITY OF HAWAI‘I AT MĀNOA
FOOD SCIENCE AND HUMAN NUTRITION PROGRAM AND HUMAN NUTRITION PROGRAM E mālama
‘ia nā pono o ka ‘āina e na ‘ōpio The traditions of the land are perpetuated by
its youth Introduction | 867
Page number: 908


Score: 0.2116
Text:
Students Noemi Arceo Caacbay Noemi Arceo Caacbay is a Masters Student in the
Public Health, Health Policy and Management Program at the University of Hawai‘

The first result looks to have nailed it!

We get a very relevant answer to our query `"macronutrients functions"` even though its quite vague.

That's the power of semantic search!

And even better, if we wanted to inspect the result further, we get the page number where the text appears.

How about we check the page to verify?

We can do so by loading the page number containing the highest result (page 5 but really page 5 + 41 since our PDF page numbers start on page 41).

Nice!

Now we can do extra research if we'd like.

We could repeat this workflow for any kind of query we'd like on our textbook.

And it would also work for other datatypes too.

We could use semantic search on customer support documents.

Or email threads.

Or company plans.

Or our old journal entries.

Almost anything!

The workflow is the same:

`ingest documents -> split into chunks -> embed chunks -> make a query -> embed the query -> compare query embedding to chunk embeddings`

And we get relevant resources *along with* the source they came from!

That's the **retrieval** part of Retrieval Augmented Generation (RAG).

Before we get to the next two steps, let's take a small aside and discuss similarity measures.

### Similarity measures: dot product and cosine similarity

Let's talk similarity measures between vectors.

Specifically, embedding vectors which are representations of data with magnitude and direction in high dimensional space (our embedding vectors have 768 dimensions).

Two of the most common you'll across are the dot product and cosine similarity.

They are quite similar.

The main difference is that cosine similarity has a normalization step.

| Similarity measure | Description | Code |
| ----- | ----- | ----- |
| [Dot Product](https://en.wikipedia.org/wiki/Dot_product) | - Measure of magnitude and direction between two vectors<br>- Vectors that are aligned in direction and magnitude have a higher positive value<br>- Vectors that are opposite in direction and magnitude have a higher negative value | [`torch.dot`](https://pytorch.org/docs/stable/generated/torch.dot.html), [`np.dot`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html), [`sentence_transformers.util.dot_score`](https://www.sbert.net/docs/package_reference/util.html#sentence_transformers.util.dot_score) |
| [Cosine Similarity](https://en.wikipedia.org/wiki/Cosine_similarity) | - Vectors get normalized by magnitude/[Euclidean norm](https://en.wikipedia.org/wiki/Norm_(mathematics))/L2 norm so they have unit length and are compared more so on direction<br>- Vectors that are aligned in direction have a value close to 1<br>- Vectors that are opposite in direction have a value close to -1 | [`torch.nn.functional.cosine_similarity`](https://pytorch.org/docs/stable/generated/torch.nn.functional.cosine_similarity.html), [`1 - scipy.spatial.distance.cosine`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cosine.html) (subtract the distance from 1 for similarity measure), [`sentence_transformers.util.cos_sim`](https://www.sbert.net/docs/package_reference/util.html#sentence_transformers.util.cos_sim) |

For text similarity, you generally want to use cosine similarity as you are after the semantic measurements (direction) rather than magnitude.

In our case, our embedding model `all-mpnet-base-v2` outputs normalized outputs (see the [Hugging Face model card](https://huggingface.co/sentence-transformers/all-mpnet-base-v2#usage-huggingface-transformers) for more on this) so dot product and cosine similarity return the same results. However, dot product is faster due to not need to perform a normalize step.

To make things bit more concrete, let's make simple dot product and cosine similarity functions and view their results on different vectors.

> **Note:** Similarity measures between vectors and embeddings can be used on any kind of embeddings, not just text embeddings. For example, you could measure image embedding similarity or audio embedding similarity. Or with text and image models like [CLIP](https://github.com/mlfoundations/open_clip), you can measure the similarity between text and image embeddings.

In [ ]:
import torch

def dot_product(vector1, vector2):
    return torch.dot(vector1, vector2)

def cosine_similarity(vector1, vector2):
    dot_product = torch.dot(vector1, vector2)

    # Get Euclidean/L2 norm of each vector (removes the magnitude, keeps direction)
    norm_vector1 = torch.sqrt(torch.sum(vector1**2))
    norm_vector2 = torch.sqrt(torch.sum(vector2**2))

    return dot_product / (norm_vector1 * norm_vector2)

# Example tensors
vector1 = torch.tensor([1, 2, 3], dtype=torch.float32)
vector2 = torch.tensor([1, 2, 3], dtype=torch.float32)
vector3 = torch.tensor([4, 5, 6], dtype=torch.float32)
vector4 = torch.tensor([-1, -2, -3], dtype=torch.float32)

# Calculate dot product
print("Dot product between vector1 and vector2:", dot_product(vector1, vector2))
print("Dot product between vector1 and vector3:", dot_product(vector1, vector3))
print("Dot product between vector1 and vector4:", dot_product(vector1, vector4))

# Calculate cosine similarity
print("Cosine similarity between vector1 and vector2:", cosine_similarity(vector1, vector2))
print("Cosine similarity between vector1 and vector3:", cosine_similarity(vector1, vector3))
print("Cosine similarity between vector1 and vector4:", cosine_similarity(vector1, vector4))

Dot product between vector1 and vector2: tensor(14.)
Dot product between vector1 and vector3: tensor(32.)
Dot product between vector1 and vector4: tensor(-14.)
Cosine similarity between vector1 and vector2: tensor(1.0000)
Cosine similarity between vector1 and vector3: tensor(0.9746)
Cosine similarity between vector1 and vector4: tensor(-1.0000)


Notice for both dot product and cosine similarity the comparisons of `vector1` and `vector2` are the opposite of `vector1` and `vector4`.

Comparing `vector1` and `vector2` both equations return positive values (14 for dot product and 1.0 for cosine similarity).

But comparing `vector1` and `vector4` the result is in the negative direction.

This makes sense because `vector4` is the negative version of `vector1`.

Whereas comparing `vector1` and `vector3` shows a different outcome.

For the dot product, the value is positive and larger then the comparison of two exactly the same vectors (32 vs 14).

However, for the cosine similarity, thanks to the normalization step, comparing `vector1` and `vector3` results in a postive value close to 1 but not exactly 1.

It is because of this that when comparing text embeddings, cosine similarity is generally favoured as it measures the difference in direction of a pair of vectors rather than difference in magnitude.

And it is this difference in direction that is more generally considered to capture the semantic meaning/vibe of the text.

The good news is that as mentioned before, the outputs of our embedding model `all-mpnet-base-v2` are already normalized.

So we can continue using the dot product (cosine similarity is dot product + normalization).

With similarity measures explained, let's functionize our semantic search steps from above so we can repeat them.

### Functionizing our semantic search pipeline

Let's put all of the steps from above for semantic search into a function or two so we can repeat the workflow.

In [ ]:
def retrieve_relevant_resources(query: str,
                                embeddings: torch.tensor,
                                model: SentenceTransformer=embedding_model,
                                n_resources_to_return: int=5,
                                print_time: bool=True):
    """
    Embeds a query with model and returns top k scores and indices from embeddings.
    """

    # Embed the query
    query_embedding = model.encode(query,
                                   convert_to_tensor=True)

    # Get dot product scores on embeddings
    start_time = timer()
    dot_scores = util.dot_score(query_embedding, embeddings)[0]
    end_time = timer()

    if print_time:
        print(f"[INFO] Time taken to get scores on {len(embeddings)} embeddings: {end_time-start_time:.5f} seconds.")

    scores, indices = torch.topk(input=dot_scores,
                                 k=n_resources_to_return)

    return scores, indices

def print_top_results_and_scores(query: str,
                                 embeddings: torch.tensor,
                                 pages_and_chunks: list[dict]=pages_and_chunks,
                                 n_resources_to_return: int=5):
    """
    Takes a query, retrieves most relevant resources and prints them out in descending order.

    Note: Requires pages_and_chunks to be formatted in a specific way (see above for reference).
    """

    scores, indices = retrieve_relevant_resources(query=query,
                                                  embeddings=embeddings,
                                                  n_resources_to_return=n_resources_to_return)

    print(f"Query: {query}\n")
    print("Results:")
    # Loop through zipped together scores and indicies
    for score, index in zip(scores, indices):
        print(f"Score: {score:.4f}")
        # Print relevant sentence chunk (since the scores are in descending order, the most relevant chunk will be first)
        print_wrapped(pages_and_chunks[index]["sentence_chunk"])
        # Print the page number too so we can reference the textbook further and check the results
        print(f"Page number: {pages_and_chunks[index]['page_number']}")
        print("\n")

Excellent! Now let's test our functions out.

In [ ]:
query = "Yemekte Domuz Eti Var Mı? "

# Get just the scores and indices of top related results
scores, indices = retrieve_relevant_resources(query=query,
                                              embeddings=embeddings)
scores, indices

[INFO] Time taken to get scores on 1651 embeddings: 0.00006 seconds.


(tensor([0.2262, 0.1936, 0.1935, 0.1793, 0.1750], device='cuda:0'),
 tensor([ 933,   62, 1242,  898,  430], device='cuda:0'))

In [ ]:
# Print out the texts of the top scores
print_top_results_and_scores(query=query,
                             embeddings=embeddings)

[INFO] Time taken to get scores on 1651 embeddings: 0.00006 seconds.
Query: Yemekte Domuz Eti Var Mı? 

Results:
Score: 0.2262
recommended that users complete these activities using a desktop or laptop
computer and in Google Chrome.   An interactive or media element has been
excluded from this version of the text. You can view it online here: http:/
/pressbooks.oer.hawaii.edu/ humannutrition2/?p=386   674 | Zinc
Page number: 715


Score: 0.1936
available in the web-based textbook and not available in the downloadable
versions (EPUB, Digital PDF, Print_PDF, or Open Document). Learning activities
may be used across various mobile devices, however, for the best user experience
it is strongly recommended that users complete these activities using a desktop
or laptop computer and in Google Chrome.   An interactive or media element has
been excluded from this version of the text. You can view it online here: http:/
/pressbooks.oer.hawaii.edu/ humannutrition2/?p=52   20 | Units of Measure
Pag

### Semantic search/vector search extensions

We've covered an exmaple of using embedding vector search to find relevant results based on a query.

However, you could also add to this pipeline with traditional keyword search.

Many modern search systems use keyword and vector search in tandem.

Our dataset is small and allows for an exhaustive search (comparing the query to *every* possible result) but if you start to work with large scale datasets with hundred of thousands, millions or even billions of vectors, you'll want to implement an index.

You can think of an index as sorting your embeddings before you search through them.

So it narrows down the search space.

For example, it would be inefficient to search every word in the dictionary to find the word "duck", instead you'd go straight to the letter D, perhaps even straight to the back half of the letter D, find words close to "duck" before finding it.

That's how an index can help search through many examples without comprimising too much on speed or quality (for more on this, check out [nearest neighbour search](https://en.wikipedia.org/wiki/Nearest_neighbor_search)).

One of the most popular indexing libraries is [Faiss](https://github.com/facebookresearch/faiss).

Faiss is open-source and was originally created by Facebook to deal with internet-scale vectors and implements many algorithms such as [HNSW](https://arxiv.org/abs/1603.09320) (Hierarchical Naviganle Small Worlds).

### Getting an LLM for local generation

We're got our retrieval pipeline ready, let's now get the generation side of things happening.

To perform generation, we're going to use a Large Language Model (LLM).

LLMs are designed to generate an output given an input.

In our case, we want our LLM to generate and output of text given a input of text.

And more specifically, we want the output of text to be generated based on the context of relevant information to the query.

The input to an LLM is often referred to as a prompt.

We'll augment our prompt with a query as well as context from our textbook related to that query.

> **Which LLM should I use?**

There are many LLMs available.

Two of the main questions to ask from this is:
1. Do I want it to run locally?
2. If yes, how much compute power can I dedicate?

If you're after the absolute best performance, you'll likely want to use an API (not running locally) such as GPT-4 or Claude 3. However, this comes with the tradeoff of sending your data away and then awaiting a response.

For our case, since we want to set up a local pipeline and run it on our own GPU, we'd answer "yes" to the first question and then the second question will depend on what hardware we have available.

To find open-source LLMs, one great resource is the [Hugging Face open LLM leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard).

The leaderboard compares many of the latest and greatest LLMs on various benchmarks.

Another great resource is [TheBloke on Hugging Face](https://huggingface.co/TheBloke), an account which provides an extensive range of quantized (models that have been made smaller) LLMs.

A rule of thumb for LLMs (and deep learning models in general) is that the higher the number of parameters, the better the model performs.

It may be tempting to go for the largest size model (e.g. a 70B parameter model rather than a 7B parameter model) but a larger size model may not be able to run on your available hardware.

The following table gives an insight into how much GPU memory you'll need to load an LLM with different sizes and different levels of [numerical precision](https://en.wikipedia.org/wiki/Precision_(computer_science)).

They are based on the fact that 1 float32 value (e.g. `0.69420`) requires 4 bytes of memory and 1GB is approximately 1,000,000,000 (one billion) bytes.

| Model Size (Billion Parameters) | Float32 VRAM (GB) | Float16 VRAM (GB) | 8-bit VRAM (GB) | 4-bit VRAM (GB) |
|-----|-----|-----|-----|-----|
| 1B                              | ~4                | ~2                | ~1              | ~0.5            |
| 7B (e.g., [Llama 2 7B](https://huggingface.co/meta-llama/Llama-2-7b), [Gemma 7B](https://huggingface.co/google/gemma-7b-it), [Mistral 7B](https://huggingface.co/mistralai/Mistral-7B-v0.1))             | ~28               | ~14               | ~7              | ~3.5            |
| 10B                             | ~40               | ~20               | ~10             | ~5              |
| 70B (e.g, Llama 2 70B)          | ~280              | ~140              | ~70             | ~35             |
| 100B                            | ~400              | ~200              | ~100            | ~50             |
| 175B                            | ~700              | ~350              | ~175            | ~87.5           |

<br>

> **Note:** Loading a model in a lower precision (e.g. 8-bit instead of float16) generally lowers performance. Lower precision can help to reduce computing requirements, however sometimes the performance degradation in terms of model output can be substantial. Finding the right speed/performance tradeoff will often require many experiments.

### Checking local GPU memory availability

Let's find out what hardware we've got available and see what kind of model(s) we'll be able to load.

> **Note:** You can also check this with the `!nvidia-smi` command.

In [ ]:
# Get GPU available memory
import torch
gpu_memory_bytes = torch.cuda.get_device_properties(0).total_memory
gpu_memory_gb = round(gpu_memory_bytes / (2**30))
print(f"Available GPU memory: {gpu_memory_gb} GB")

Available GPU memory: 22 GB


Ok wonderful!

I'm running this notebook with a NVIDIA RTX 4090, so I've got 24GB of VRAM available.

However, this may be different on your end.

Looking at the table above, it seems we can run a ~7-10B parameter model in float16 precision pretty comfortably.

But we could also run a smaller one if we'd like.

Let's try out the recently released (at the time of writing, March 2024) LLM from Google, [Gemma](https://huggingface.co/blog/gemma).

Specifically, we'll use the `gemma-7b-it` version which stands for Gemma 7B Instruction-Tuned.

Instruction tuning is the process of tuning a raw language model to follow instructions.

These are the kind of models you'll find in most chat-based assistants such as ChatGPT, Gemini or Claude.

The following table shows different amounts of GPU memory requirements for different verions of the Gemma LLMs with varying levels of precision.

| Model             | Precision | Min-Memory (Bytes) | Min-Memory (MB) | Min-Memory (GB) | Recommended Memory (GB) | Hugging Face ID |
|-------------------|-----------|----------------|-------------|-------------| ----- | ----- |
| [Gemma 2B](https://huggingface.co/google/gemma-2b-it)          | 4-bit     | 2,106,749,952  | 2009.15     | 1.96        | ~5.0 | [`gemma-2b`](https://huggingface.co/google/gemma-2b) or [`gemma-2b-it`](https://huggingface.co/google/gemma-2b-it) for instruction tuned version |
| Gemma 2B          | Float16   | 5,079,453,696  | 4844.14     | 4.73        | ~8.0 | Same as above |
| [Gemma 7B](https://huggingface.co/google/gemma-7b-it)          | 4-bit     | 5,515,859,968  | 5260.33     | 5.14        | ~8.0 | [`gemma-7b`](https://huggingface.co/google/gemma-7b) or [`gemma-7b-it`](https://huggingface.co/google/gemma-7b-it) for instruction tuned version |
| Gemma 7B          | Float16   | 17,142,470,656 | 16348.33    | 15.97       | ~19 | Same as above |

> **Note:** `gemma-7b-it` means "instruction tuned", as in, a base LLM (`gemma-7b`) has been fine-tuned to follow instructions, similar to [`Mistral-7B-v0.1`](https://huggingface.co/mistralai/Mistral-7B-v0.1) and [`Mistral-7B-Instruct-v0.1`](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1).
>
> There are also further quantized and smaller variants of Gemma (and other LLMs) available in various formats such as GGUF. You can see many of these on [TheBloke account on Hugging Face](https://huggingface.co/TheBloke).
>
> The version of LLM you choose to use will be largely based on project requirements and experimentation.

Based on the table above, let's write a simple if/else statement which recommends which Gemma variant we should look into using.

In [ ]:
import os
os.environ["HF_TOKEN"] = "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"

In [ ]:
# Note: the following is Gemma focused, however, there are more and more LLMs of the 2B and 7B size appearing for local use.
if gpu_memory_gb < 5.1:
    print(f"Your available GPU memory is {gpu_memory_gb}GB, you may not have enough memory to run a Gemma LLM locally without quantization.")
elif gpu_memory_gb < 8.1:
    print(f"GPU memory: {gpu_memory_gb} | Recommended model: Gemma 2B in 4-bit precision.")
    use_quantization_config = True
    model_id = "google/gemma-2b-it"
elif gpu_memory_gb < 19.0:
    print(f"GPU memory: {gpu_memory_gb} | Recommended model: Gemma 2B in float16 or Gemma 7B in 4-bit precision.")
    use_quantization_config = True
    model_id = "google/gemma-7b-it"
elif gpu_memory_gb > 19.0:
    print(f"GPU memory: {gpu_memory_gb} | Recommend model: Gemma 7B in 4-bit or float16 precision.")
    use_quantization_config = False
    model_id = "google/gemma-7b-it"

print(f"use_quantization_config set to: {use_quantization_config}")
print(f"model_id set to: {model_id}")

GPU memory: 22 | Recommend model: Gemma 7B in 4-bit or float16 precision.
use_quantization_config set to: False
model_id set to: google/gemma-7b-it


### Loading an LLM locally

Alright! Looks like `gemma-7b-it` it is (for my local machine with an RTX 4090, change the `model_id` and `use_quantization_config` values to suit your needs)!

There are plenty of examples of how to load the model on the `gemma-7b-it` [Hugging Face model card](https://huggingface.co/google/gemma-7b-it).

Good news is, the Hugging Face [`transformers`](https://huggingface.co/docs/transformers/) library has all the tools we need.

To load our LLM, we're going to need a few things:
1. A quantization config (optional) - This will determine whether or not we load the model in 4bit precision for lower memory usage. The we can create this with the [`transformers.BitsAndBytesConfig`](https://huggingface.co/docs/transformers/v4.38.2/en/main_classes/quantization#transformers.BitsAndBytesConfig) class (requires installing the [`bitsandbytes` library](https://github.com/TimDettmers/bitsandbytes)).
2. A model ID - This is the reference Hugging Face model ID which will determine which tokenizer and model gets used. For example `gemma-7b-it`.
3. A tokenzier - This is what will turn our raw text into tokens ready for the model. We can create it using the [`transformers.AutoTokenzier.from_pretrained`](https://huggingface.co/docs/transformers/v4.38.2/en/model_doc/auto#transformers.AutoTokenizer) method and passing it our model ID.
4. An LLM model - Again, using our model ID we can load a specific LLM model. To do so we can use the [`transformers.AutoModelForCausalLM.from_pretrained`](https://huggingface.co/docs/transformers/model_doc/auto#transformers.AutoModelForCausalLM.from_pretrained) method and passing it our model ID as well as other various parameters.

As a bonus, we'll check if [Flash Attention 2](https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2) is available using `transformers.utils.is_flash_attn_2_available()`. Flash Attention 2 speeds up the attention mechanism in Transformer architecture models (which is what many modern LLMs are based on, including Gemma). So if it's available and the model is supported (not all models support Flash Attention 2), we'll use it. If it's not available, you can install it by following the instructions on the [GitHub repo](https://github.com/Dao-AILab/flash-attention).

> **Note:** Flash Attention 2 currently works on NVIDIA GPUs with a compute capability score of 8.0+ (Ampere, Ada Lovelace, Hopper architectures). We can check our GPU compute capability score with [`torch.cuda.get_device_capability(0)`](https://pytorch.org/docs/stable/generated/torch.cuda.get_device_capability.html).

> **Note:** To get access to the Gemma models, you will have to [agree to the terms & conditions](https://huggingface.co/google/gemma-7b-it) on the Gemma model page on Hugging Face. You will then have to authorize your local machine via the [Hugging Face CLI/Hugging Face Hub `login()` function](https://huggingface.co/docs/huggingface_hub/en/quick-start#authentication). Once you've done this, you'll be able to download the models. If you're using Google Colab, you can add a [Hugging Face token](https://huggingface.co/docs/hub/en/security-tokens) to the "Secrets" tab.
>
> Downloading an LLM locally can take a fair bit of time depending on your internet connection. Gemma 7B is about a 16GB download and Gemma 2B is about a 6GB download.

Let's do it!

In [ ]:
!export CUDA_LAUNCH_BLOCKING=1

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers.utils import is_flash_attn_2_available

# 1. Create quantization config for smaller model loading (optional)
# Requires !pip install bitsandbytes accelerate, see: https://github.com/TimDettmers/bitsandbytes, https://huggingface.co/docs/accelerate/
# For models that require 4-bit quantization (use this if you have low GPU memory available)
from transformers import BitsAndBytesConfig
quantization_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16)

# Bonus: Setup Flash Attention 2 for faster inference, default to "sdpa" or "scaled dot product attention" if it's not available
# Flash Attention 2 requires NVIDIA GPU compute capability of 8.0 or above, see: https://developer.nvidia.com/cuda-gpus
# Requires !pip install flash-attn, see: https://github.com/Dao-AILab/flash-attention
if (is_flash_attn_2_available()) and (torch.cuda.get_device_capability(0)[0] >= 8):
  attn_implementation = "flash_attention_2"
else:
  attn_implementation = "sdpa"
print(f"[INFO] Using attention implementation: {attn_implementation}")

# 2. Pick a model we'd like to use (this will depend on how much GPU memory you have available)
#model_id = "google/gemma-7b-it"
model_id = model_id # (we already set this above)
print(f"[INFO] Using model_id: {model_id}")

# 3. Instantiate tokenizer (tokenizer turns text into numbers ready for the model)
tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path=model_id)

# 4. Instantiate the model
llm_model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path=model_id,
                                                 torch_dtype=torch.float16, # datatype to use, we want float16
                                                 quantization_config=quantization_config if use_quantization_config else None,
                                                 low_cpu_mem_usage=False, # use full memory
                                                 attn_implementation=attn_implementation) # which attention version to use

if not use_quantization_config: # quantization takes care of device setting automatically, so if it's not used, send model to GPU
    llm_model.to("cuda")

[INFO] Using attention implementation: flash_attention_2
[INFO] Using model_id: google/gemma-7b-it


tokenizer_config.json:   0%|          | 0.00/397 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/804 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/5.22M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.62M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/20.9k [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/2.11G [00:00<?, ?B/s]

You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.


Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

We've got an LLM!

Let's check it out.

In [ ]:
llm_model

GemmaForCausalLM(
  (model): GemmaModel(
    (embed_tokens): Embedding(256000, 3072, padding_idx=0)
    (layers): ModuleList(
      (0-27): 28 x GemmaDecoderLayer(
        (self_attn): GemmaFlashAttention2(
          (q_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (k_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (v_proj): Linear(in_features=3072, out_features=4096, bias=False)
          (o_proj): Linear(in_features=4096, out_features=3072, bias=False)
          (rotary_emb): GemmaRotaryEmbedding()
        )
        (mlp): GemmaMLP(
          (gate_proj): Linear(in_features=3072, out_features=24576, bias=False)
          (up_proj): Linear(in_features=3072, out_features=24576, bias=False)
          (down_proj): Linear(in_features=24576, out_features=3072, bias=False)
          (act_fn): PytorchGELUTanh()
        )
        (input_layernorm): GemmaRMSNorm()
        (post_attention_layernorm): GemmaRMSNorm()
      )
    )
    (norm): Ge

Ok, ok a bunch of layers ranging from embedding layers to attention layers (see the `GemmaFlashAttention2` layers!) to MLP and normalization layers.

The good news is that we don't have to know too much about these to use the model.

How about we get the number of parameters in our model?

In [ ]:
def get_model_num_params(model: torch.nn.Module):
    return sum([param.numel() for param in model.parameters()])

get_model_num_params(llm_model)

8537680896

Hmm, turns out that Gemma 7B is really Gemma 8.5B.

It pays to do your own investigations!

How about we get the models memory requirements?

Nice, looks like this model takes up 15.97GB of space on the GPU.

Plus a little more for the forward pass (due to all the calculations happening between the layers).

Hence why I rounded it up to be ~19GB in the table above.

Now let's get to the fun part, generating some text!

### Generating text with our LLM

We can generate text with our LLM `model` instance by calling the [`generate()` method](https://huggingface.co/docs/transformers/v4.38.2/en/main_classes/text_generation#transformers.GenerationConfig) (this method has plenty of options to pass into it alongside the text) on it and passing it a tokenized input.

The tokenized input comes from passing a string of text to our `tokenizer`.

It's important to note that you should use a tokenizer that has been paired with a model.

Otherwise if you try to use a different tokenizer and then pass those inputs to a model, you will likely get errors/strange results.

For some LLMs, there's a specific template you should pass to them for ideal outputs.

For example, the `gemma-7b-it` model has been trained in a dialogue fashion (instruction tuning).

In this case, our `tokenizer` has a [`apply_chat_template()` method](https://huggingface.co/docs/transformers/main/en/internal/tokenization_utils#transformers.PreTrainedTokenizerBase.apply_chat_template) which can prepare our input text in the right format for the model.

Let's try it out.

> **Note:** The following demo has been modified from the Hugging Face model card for [Gemma 7B](https://huggingface.co/google/gemma-7b-it). Many similar demos of usage are available on the model cards of similar models.

In [ ]:
input_text = "Sitenizde Rezervasyon ile ilgili sorun yaşadım"
print(f"Input text:\n{input_text}")

# Create prompt template for instruction-tuned model
dialogue_template = [
    {"role": "user",
     "content": input_text}
]

# Apply the chat template
prompt = tokenizer.apply_chat_template(conversation=dialogue_template,
                                       tokenize=False, # keep as raw text (not tokenized)
                                       add_generation_prompt=True)
print(f"\nPrompt (formatted):\n{prompt}")

No chat template is set for this tokenizer, falling back to a default class-level template. This is very error-prone, because models are often trained with templates different from the class default! Default chat templates are a legacy feature and will be removed in Transformers v4.43, at which point any code depending on them will stop working. We recommend setting a valid chat template before then to ensure that this model continues working without issues.


Input text:
Sitenizde Rezervasyon ile ilgili sorun yaşadım

Prompt (formatted):
<|im_start|>user
Sitenizde Rezervasyon ile ilgili sorun yaşadım<|im_end|>
<|im_start|>assistant



Notice the scaffolding around our input text, this is the kind of turn-by-turn instruction tuning our model has gone through.

Our next step is to tokenize this formatted text and pass it to our model's `generate()` method.

We'll make sure our tokenized text is on the same device as our model (GPU) using `to("cuda")`.

Let's generate some text!

We'll time it for fun with the `%%time` magic.

In [ ]:
%%time

# Tokenize the input text (turn it into numbers) and send it to GPU
input_ids = tokenizer(prompt, return_tensors="pt").to("cuda")
print(f"Model input (tokenized):\n{input_ids}\n")

# Generate outputs passed on the tokenized input
# See generate docs: https://huggingface.co/docs/transformers/v4.38.2/en/main_classes/text_generation#transformers.GenerationConfig
outputs = llm_model.generate(**input_ids,
                             max_new_tokens=256) # define the maximum number of new tokens to create
print(f"Model output (tokens):\n{outputs[0]}\n")

Model input (tokenized):
{'input_ids': tensor([[   101,    133,    197,  15419,    168,  17922,    197,    135,  21590,
         117076, 261102,  17436,  27176, 167332,  15462,  21578,  64635, 332271,
          15007,    133,    197,  15419,    168,  16706,    197,    135,    133,
            197,  15419,    168,  17922,    197,    135,  86941,    102]],
       device='cuda:0'), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0')}



ValueError: The following `model_kwargs` are not used by the model: ['token_type_ids'] (note: typos in the generate arguments will also show up in this list)

In [ ]:
%%time

# Tokenize the input text (turn it into numbers) and send it to GPU
input_ids = tokenizer(prompt, return_tensors="pt", truncation=True).to("cuda") # Added truncation
print(f"Model input (tokenized):\n{input_ids['input_ids']}\n") # Only print the input_ids

# Generate outputs passed on the tokenized input
# See generate docs: https://huggingface.co/docs/transformers/v4.38.2/en/main_classes/text_generation#transformers.GenerationConfig
outputs = llm_model.generate(input_ids['input_ids'], # Pass only the input_ids
                             max_new_tokens=256) # define the maximum number of new tokens to create
print(f"Model output (tokens):\n{outputs[0]}\n")

Model input (tokenized):
tensor([[   101,    133,    197,  15419,    168,  17922,    197,    135,  21590,
         117076, 261102,  17436,  27176, 167332,  15462,  21578,  64635, 332271,
          15007,    133,    197,  15419,    168,  16706,    197,    135,    133,
            197,  15419,    168,  17922,    197,    135,  86941,    102]],
       device='cuda:0')



RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Woohoo! We just generated some text on our local GPU!

Well not just yet...

Our LLM accepts tokens in and sends tokens back out.

We can conver the output tokens to text using [`tokenizer.decode()`](https://huggingface.co/docs/transformers/main_classes/tokenizer#transformers.PreTrainedTokenizer.decode).

In [ ]:
# Decode the output tokens to text
outputs_decoded = tokenizer.decode(outputs[0])
print(f"Model output (decoded):\n{outputs_decoded}\n")

NameError: name 'outputs' is not defined

Woah! That looks like a pretty good answer.

But notice how the output contains the prompt text as well?

How about we do a little formatting to replace the prompt in the output text?

> **Note:** `"<bos>"` and `"<eos>"` are special tokens to denote "beginning of sentence" and "end of sentence" respectively.

In [ ]:
print(f"Input text: {input_text}\n")
print(f"Output text:\n{outputs_decoded.replace(prompt, '').replace('<bos>', '').replace('<eos>', '')}")

How cool is that!

We just officially generated text from an LLM running locally.

So we've covered the R (retrieval) and G (generation) of RAG.

How about we check out the last step?

Augmentation.

First, let's put together a list of queries we can try out with our pipeline.

And now let's check if our `retrieve_relevant_resources()` function works with our list of queries.

Beautiful!

Let's augment!

### Augmenting our prompt with context items

What we'd like to do with augmentation is take the results from our search for relevant resources and put them into the prompt that we pass to our LLM.

In essence, we start with a base prompt and update it with context text.

Let's write a function called `prompt_formatter` that takes in a query and our list of context items (in our case it'll be select indices from our list of dictionaries inside `pages_and_chunks`) and then formats the query with text from the context items.

We'll apply the dialogue and chat template to our prompt before returning it as well.

> **Note:** The process of augmenting or changing a prompt to an LLM is known as prompt engineering. And the best way to do it is an active area of research. For a comprehensive guide on different prompt engineering techniques, I'd recommend the Prompt Engineering Guide ([promptingguide.ai](https://www.promptingguide.ai/)), [Brex's Prompt Engineering Guide](https://github.com/brexhq/prompt-engineering) and the paper [Prompt Design and Engineering: Introduction and Advanced Models](https://arxiv.org/abs/2401.14423).

In [ ]:
def prompt_formatter(query: str,
                     context_items: list[dict]) -> str:
    """
    Augments query with text-based context from context_items.
    """
    # Join context items into one dotted paragraph
    context = "- " + "\n- ".join([item["sentence_chunk"] for item in context_items])

    # Create a base prompt with examples to help the model
    # Note: this is very customizable, I've chosen to use 3 examples of the answer style we'd like.
    # We could also write this in a txt file and import it in if we wanted.
    base_prompt = """Based on the following context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering the query.
Don't return the thinking, only return the answer.
Make sure your answers are as explanatory as possible.
Use the following examples as reference for the ideal answer style.
\nExample 1:
Query: What are the fat-soluble vitamins?
Answer: The fat-soluble vitamins include Vitamin A, Vitamin D, Vitamin E, and Vitamin K. These vitamins are absorbed along with fats in the diet and can be stored in the body's fatty tissue and liver for later use. Vitamin A is important for vision, immune function, and skin health. Vitamin D plays a critical role in calcium absorption and bone health. Vitamin E acts as an antioxidant, protecting cells from damage. Vitamin K is essential for blood clotting and bone metabolism.
\nExample 2:
Query: What are the causes of type 2 diabetes?
Answer: Type 2 diabetes is often associated with overnutrition, particularly the overconsumption of calories leading to obesity. Factors include a diet high in refined sugars and saturated fats, which can lead to insulin resistance, a condition where the body's cells do not respond effectively to insulin. Over time, the pancreas cannot produce enough insulin to manage blood sugar levels, resulting in type 2 diabetes. Additionally, excessive caloric intake without sufficient physical activity exacerbates the risk by promoting weight gain and fat accumulation, particularly around the abdomen, further contributing to insulin resistance.
\nExample 3:
Query: What is the importance of hydration for physical performance?
Answer: Hydration is crucial for physical performance because water plays key roles in maintaining blood volume, regulating body temperature, and ensuring the transport of nutrients and oxygen to cells. Adequate hydration is essential for optimal muscle function, endurance, and recovery. Dehydration can lead to decreased performance, fatigue, and increased risk of heat-related illnesses, such as heat stroke. Drinking sufficient water before, during, and after exercise helps ensure peak physical performance and recovery.
\nNow use the following context items to answer the user query:
{context}
\nRelevant passages: <extract relevant passages from the context here>
User query: {query}
Answer:"""

    # Update base prompt with context items and query
    base_prompt = base_prompt.format(context=context, query=query)

    # Create prompt template for instruction-tuned model
    dialogue_template = [
        {"role": "user",
        "content": base_prompt}
    ]

    # Apply the chat template
    prompt = tokenizer.apply_chat_template(conversation=dialogue_template,
                                          tokenize=False,
                                          add_generation_prompt=True)
    return prompt

Looking good! Let's try our function out.

What a good looking prompt!

We can tokenize this and pass it straight to our LLM.

In [ ]:
%%time

input_ids = tokenizer(prompt, return_tensors="pt").to("cuda")

# Generate an output of tokens
outputs = llm_model.generate(**input_ids,
                             temperature=0.7, # lower temperature = more deterministic outputs, higher temperature = more creative outputs
                             do_sample=True, # whether or not to use sampling, see https://huyenchip.com/2024/01/16/sampling.html for more
                             max_new_tokens=256) # how many new tokens to generate from prompt

# Turn the output tokens into text
output_text = tokenizer.decode(outputs[0])

print(f"Query: {query}")
print(f"RAG answer:\n{output_text.replace(prompt, '')}")

Yesssssss!!!

Our RAG pipeline is complete!

We just Retrieved, Augmented and Generated!

And all on our own local GPU!

How about we functionize the generation step to make it easier to use?

We can put a little formatting on the text being returned to make it look nice too.

And we'll make an option to return the context items if needed as well.

In [ ]:
def ask(query,
        temperature=0.7,
        max_new_tokens=512,
        format_answer_text=True,
        return_answer_only=True):
    """
    Takes a query, finds relevant resources/context and generates an answer to the query based on the relevant resources.
    """

    # Get just the scores and indices of top related results
    scores, indices = retrieve_relevant_resources(query=query,
                                                  embeddings=embeddings)

    # Create a list of context items
    context_items = [pages_and_chunks[i] for i in indices]

    # Add score to context item
    for i, item in enumerate(context_items):
        item["score"] = scores[i].cpu() # return score back to CPU

    # Format the prompt with context items
    prompt = prompt_formatter(query=query,
                              context_items=context_items)

    # Tokenize the prompt
    input_ids = tokenizer(prompt, return_tensors="pt").to("cuda")

    # Generate an output of tokens
    outputs = llm_model.generate(**input_ids,
                                 temperature=temperature,
                                 do_sample=True,
                                 max_new_tokens=max_new_tokens)

    # Turn the output tokens into text
    output_text = tokenizer.decode(outputs[0])

    if format_answer_text:
        # Replace special tokens and unnecessary help message
        output_text = output_text.replace(prompt, "").replace("<bos>", "").replace("<eos>", "").replace("Sure, here is the answer to the user query:\n\n", "")

    # Only return the answer without the context items
    if return_answer_only:
        return output_text

    return output_text

In [ ]:
query = "Glutensiz yemek seçenekleriniz var mı"

print(f"Query: {query}")

# Answer query with context and return context
answer = ask(query=query,
                            temperature=0.7,
                            max_new_tokens=512,
                            return_answer_only=False)

print(f"Answer:\n")
print_wrapped(answer)


In [ ]:
!pip install git+https://github.com/openai/whisper.git

In [ ]:
import gradio as gr
import torch
import whisper

# Whisper modelini yükleme
model = whisper.load_model("base")

def transcribe(audio):
    # Ses dosyasını yükleme ve yeniden örnekleme
    audio = whisper.load_audio(audio)
    audio = whisper.pad_or_trim(audio)

    # Log-Mel spectrogramını hesaplama
    mel = whisper.log_mel_spectrogram(audio).to(model.device)

    # Inference işlemi
    options = whisper.DecodingOptions(language="en")
    result = whisper.decode(model, mel, options)

    return result.text

iface = gr.Interface(
    fn=transcribe,
    inputs=gr.Audio("microphone", type="filepath"),
    outputs="text",
    title="Whisper Transcription",
    description="Record an audio and transcribe it to text using the Whisper model."
)

iface.launch()

In [ ]:
import gradio as gr

def generate_answer(query):
    answer = ask(query=query,
                                temperature=0.7,
                                max_new_tokens=512,
                                return_answer_only=False)

    return answer

iface = gr.Interface(fn=generate_answer,
                     inputs = gr.Textbox(label="Text"),
                     outputs = gr.Textbox(label="Output"),
                     )
iface.launch()

In [ ]:
import gradio as gr
import torch
import whisper

# Whisper modelini yükleme
model = whisper.load_model("base")

def transcribe_and_answer(audio, query):
    # Ses dosyasını yükleme ve yeniden örnekleme
    audio = whisper.load_audio(audio)
    audio = whisper.pad_or_trim(audio)

    # Log-Mel spectrogramını hesaplama
    mel = whisper.log_mel_spectrogram(audio).to(model.device)

    # Inference işlemi
    options = whisper.DecodingOptions(language="en")
    result = whisper.decode(model, mel, options)

    transcribed_text = result.text

    # Sorgu cevabını oluşturma
    answer = ask(query=query,
                                temperature=0.7,
                                max_new_tokens=512,
                                return_answer_only=False)

    return transcribed_text, answer

iface = gr.Interface(
    fn=transcribe_and_answer,
    inputs=[gr.Audio("microphone", type="filepath"), gr.Textbox(label="Text")],
    outputs=[gr.Textbox(label="Transcription"), gr.Textbox(label="Output")],
    title="Whisper Transcription and QA",
    description="Record an audio, transcribe it to text using the Whisper model, and generate an answer to the query."
)

iface.launch()


In [ ]:
import gradio as gr
import torch
import whisper

# Whisper modelini yükleme
model = whisper.load_model("base")

def transcribe_and_answer(audio):
    # Ses dosyasını yükleme ve yeniden örnekleme
    audio = whisper.load_audio(audio)
    audio = whisper.pad_or_trim(audio)

    # Log-Mel spectrogramını hesaplama
    mel = whisper.log_mel_spectrogram(audio).to(model.device)

    # Inference işlemi
    options = whisper.DecodingOptions(language="en")
    result = whisper.decode(model, mel, options)

    transcribed_text = result.text

    # Sorgu cevabını oluşturma
    answer= ask(query=transcribed_text,
                                temperature=0.7,
                                max_new_tokens=512,
                                return_answer_only=False)

    return transcribed_text, answer

iface = gr.Interface(
    fn=transcribe_and_answer,
    inputs=gr.Audio("microphone", type="filepath"),
    outputs=[gr.Textbox(label="Transcription"), gr.Textbox(label="Output")],
    title="Whisper Transcription and QA",
    description="Record an audio, transcribe it to text using the Whisper model, and generate an answer to the query."
)

iface.launch()


In [ ]:
import gradio as gr
import whisper

# whisper modelini yükleme
model = whisper.load_model("base")

# ses dosyasını yükleme ve yeniden örnekleme
def transcribe_and_answer(audio, text_input):
    if audio is not None:
        audio = whisper.load_audio(audio)
        audio = whisper.pad_or_trim(audio)
        mel = whisper.log_mel_spectrogram(audio).to(model.device)
        options = whisper.DecodingOptions(language="en")
        result = whisper.decode(model, mel, options)
        transcribed_text = result.text
    else:
        transcribed_text = text_input

    # Soruyu cevapla
    answer = ask(transcribed_text)
    return transcribed_text, answer

iface = gr.Interface(
    fn=transcribe_and_answer,
    inputs=[gr.Audio("microphone", type="filepath"), gr.Textbox(label="Text")],
    outputs=[gr.Textbox(label="Transcription"), gr.Textbox(label="Output")],
    title="Whisper Transcription and QA",
    description="Record an audio, transcribe it to text using the Whisper model, or type your question and get an answer.",
    theme="dark"
)


iface.launch(share=True)


### DALL·E mini/VQ-VAE İçindeki Bileşenler ve Çalışma Mekanizması

#### Genel Bakış
DALL·E mini/VQ-VAE modeli, yazılı metinlerden anlamlı görseller üretir. Bu işlem, metni kod olarak adlandırılan sıkıştırılmış temsillere dönüştürmek ve bu kodları kullanarak görseller üretmek şeklinde iki ana adımdan oluşur. VQ-VAE, bu kodlama ve kodları çözme sürecinde önemli bir bileşendir.

### Adım Adım Detaylı Çalışma Süreci

#### 1. Metin Girdisi (Prompt)
Kullanıcı modelimize bir metin girer. Örneğin, "proteinler ne işe yarar?"

#### 2. Metni Anlama ve İşleme
Metin, doğal dil işleme (NLP) teknikleriyle anlaşılır ve alt bileşenlerine ayrılır. Model, metnin anlamını çıkarır.

#### 3. VQ-VAE ile Kodlama İşlemi
Metin, Encoder (kodlayıcı) modülüne gönderilir.

##### Encoder (Kodlayıcı):
- **Latent Vektör:** Metin, Encoder tarafından düşük boyutlu bir latent vektöre dönüştürülür. Bu, metnin sıkıştırılmış bir temsilidir.
  - Örneğin: "proteinler" → [0.5, 0.7, -0.2, ...] gibi bir vektör olabilir.

##### Codebook (Kod Kitabı):
- **Diskret Vektörler:** Latent vektörün değerleri, önceden belirlenmiş kod sözcüklerine eşlenir.
  - Codebook, birçok diskret kod sözcüğü içerir.
  - **Öz:** Latent vektör, codebook'taki en yakın kod sözcüklere yuvarlanır; bu işleme "vektör kuantizasyonu" denir.

##### Örneğin:
- Latent Vektör: [0.5, 0.7, -0.2, ...]
- En Yakın Kod: [0.6, 0.8, -0.1, ...]
- Bu kod sözcükleri, codebook içinde belirli yerlere sahiptir ve sayısal olarak ifade edilir.

#### 4. Transformer ile Görselleştirme
DALL·E mini'nin transformer bileşeni, metin ve latent kodları kullanarak hangi görsel bileşenlerin üretilmesi gerektiğini belirler.

- **Girdiler ve Çıktılar:** Transformer modeli, metin girdisi ile latent kodları birleştirip anlamlı, sıkıştırılmış bir görsel temsil oluşturur.

#### 5. VQ-VAE Decoder (Kod Çözücü) ile Görüntü Üretimi
Diskret kod sözcükleri, Decoder modülüne gönderilir.

##### Decoder (Kod Çözücü):
- **Latent Vektörden Görsel Oluşturma:** Diskret kodlar, Decoder kullanılarak yeniden sürekli değerli latent vektörlere ve nihayetinde orijinal biçimine (görsel) dönüştürülür.
  - Örneğin: Kod sözcüklerinden kas yapısı, hücre yapısı, veya enzim gösterimleri gibi görsel bileşenler üretilir.

#### 6. Post-Processing:
- **Önceki adımdan gelen görseller iyileştirilir:** Gürültü azaltma, kontrast ayarlama gibi tekniklerle görüntünün kalitesi artırılır.

### Adım Adım Çalışma Örneği:

1. **Metin Girdisi:** "Proteinler ne işe yarar?"
2. **Encoder:** Bu metin, encoder tarafından latent bir vektöre dönüştürülür. (Örneğin, [0.5, 0.7, -0.2, ...])
3. **Codebook:** Bu latent vektör bir kod sözcüğüne karşılık gelir; bu kod sözcükler codebook içinde bulunan diskret temsilcilerle eşleştirilir. (Örneğin, [0.6, 0.8, -0.1, ...])
4. **Transformer:** Metin ve kodlar işlenir, hangi görsellerin üretilmesi gerektiği belirlenir.
5. **Decoder:** Diskret kodlar decoder tarafından anlamlı görsellere dönüştürülür.
6. **Post-Processing:** Üretilen görsel iyileştirilir ve son kullanıcıya sunulur.



### Stable Diffusion Modelinin Çalışma Prensibi

#### Genel Bakış
Stable Diffusion, latent diffusion modeli ailesine aittir ve görüntü üretiminde kullanılan ileri bir modeldir. "Diffusion" ya da "dağılım" süreci, bu modelin temel taşıdır.

### Adım Adım Çalışma Süreci

#### 1. Metin Girdisi (Prompt)
Kullanıcıdan belirli bir metin girdisi (ör. "güzel bir sahil manzarası") alınır. Model, bu metin girdisini anlamaya ve analiz etmeye başlar.

#### 2. Gürültülü Başlangıç
Model, başlangıçta tamamen gürültülü (yani rastgele piksellerle dolu) bir görüntü yaratır. Bu gürültülü görüntü, zamanla düzgün bir görüntüye dönüşecektir.

#### 3. Gürültü Azaltma ve Görüntü Yaratma
Stable Diffusion, bu gürültülü başlangıçtan yavaş yavaş daha anlamlı bir görüntü yaratmaya başlar. Bu sürece "diffusion" (dağılım) denir ve model, gürültüyü adım adım azaltarak görüntüyü iyileştirir.

- **Adım 1:** Gürültülü bir görüntü ile başlar.
- **Adım 2:** Gürültü bir miktar azaltılır ve bazı şekiller belirmeye başlar.
- **Adım 3:** Daha fazla gürültü çıkarılır, görüntü netleşmeye başlar.
- **Son Adım:** Gürültü tamamen giderildikten sonra net bir görüntü elde edilir.

Bu gürültü azaltma süreci, modelin çok sayıda küçük iyileştirme adımları yaparak en sonunda temiz bir görüntüye ulaşmasını sağlar.

#### 4. Encoder ve Decoder
Stable Diffusion modeli, yüksek çözünürlüklü görüntüler oluşturmak için encoder-decoder mimarisi kullanır.

- **Encoder:** Girdi metnini anlamak ve bunu sayısal bir temsile dönüştürmek için kullanılır. Bu sayısal temsil daha sonra diffusion sürecinde kullanılır.
- **Decoder:** Diffusion sürecinde üretilen latent temsillerden nihai görüntüyü üretmek için kullanılır.

### Detaylı Süreç ve Görsel Analog

- **Başlangıç Gürültüsü:** Tamamen rastgele piksellerden oluşan bir görüntü ile başlarız.
  
  Örn: [X1, X2, X3, ..., Xn]  # n sayıda rastgele piksel değeri

- **Encoded Metin Temsili:** Girdi metni, model tarafından sayısal bir latent vektöre dönüştürülür. Bu vektör, metnin anlamını içerir.

  Örn: "güzel bir sahil manzarası" -> [0.5, 0.3, -0.2, ..., 0.7]

- **Stepwise Diffusion:** Diffusion süreci, her adımda gürültüyü azaltarak önceki adımda yapılan iyileştirmeleri daha anlamlı hale getirir.

  Adım 1: Gürültülü Görüntü -> Daha Az Gürültülü Görüntü
  Adım 2: Daha Az Gürültülü Görüntü -> Şekiller Belirginleşir
  Adım 3: Şekiller Belirginleşir -> Renkler ve Detaylar Ortaya Çıkar
  Adım n: Son Net Görüntü

### Özetle Stable Diffusion Modelinin Avantajları

- **Yüksek Kaliteli Görüntüler:** Diffusion süreci sayesinde başlangıçtaki gürültüyü adım adım azaltarak yüksek kaliteli ve detaylı görüntüler üretebilir.
- **Genel Kullanım Alanları:** Sanat, tasarım, içerik yaratımı ve daha birçok alanda kullanılabilir.
- **Esneklik ve Güç:** Encoder-decoder mimarisi sayesinde esnek ve çok yönlü bir kullanım sağlar.